elastic/apm-agent-python

elasticapm/base.py, elasticapm/events.py, tests/contrib/django/django_tests.py, tests/middleware/tests.py
Instead set it for messages specifically.
=> No longer set a default log level for errors.

.travis.old.yml, .travis.yml, Makefile, elasticapm/utils/module_import.py, setup.cfg
This splits our matrix into different build stages. First we run linters (only isort so far, but we'll probably add flake8 soonish), then the whole test matrix, then the manylinux1 wheel builds.
Unfortunately, this makes the `travis.yml` much larger due to the fact that we need to spell out the whole matrix manually. According to the travis IRC channel, and independently confirmed by @watson, the implicit build matrix isn't compatible with stages.
=> travis build stages [WIP]

Makefile, docs/index.asciidoc, script/build_docs.sh
This is the basic doc structure needed for the elastic docs build. For convenience I added a script that can be executed with `make docs` to build the docs locally to see if the doc build passes and how the docs will look like.
As soon as we have Jenkins added as CI we should also add a build step for `make docs` to make sure we do not break the doc build.
=> Add basic docs structure to agent

elasticapm/conf/defaults.py, elasticapm/contrib/django/client.py, elasticapm/contrib/django/middleware/__init__.py, elasticapm/processors.py, tests/contrib/django/django_tests.py, tests/contrib/django/testapp/views.py, tests/processors/tests.py
This adds `status_code` and `headers` to the transaction data.
Unfortunately, we can't do the same for exceptions, as we do not have access to the response object in the exception handler.
=> add response data to Django transactions

tests/instrumentation/urllib3_tests.py
Using port 0 let's the OS choose a free port, which avoids rare port collisions on Travis
=> use port 0 instead of random port for TCP server in urllib3 test

Jenkinsfile
The combination was not tested previously on Travis. Some tests are failing
which should not affect the overall testrun success.
=> Allow pypy3 flask-0.11 combination to fail.

conftest.py, elasticapm/contrib/django/management/commands/elasticapm.py, elasticapm/contrib/django/middleware/__init__.py, tests/contrib/django/django_tests.py, tests/contrib/django/testapp/middleware.py, tests/instrumentation/django_tests/template_tests.py, tests/instrumentation/psycopg2_tests.py, tests/utils/compat.py
Main change is a different approach of `MIDDLEWARE_CLASSES` vs. `MIDDLEWARE`. Instead of duplicating the tests, we decide which configuration option to use at runtime.
=> series of Django 2.0 fixes

tests/instrumentation/requests_tests.py, tests/transports/test_urllib3.py
This gets rid of a lot of ugly warnings like 
tests/instrumentation/requests_tests.py::InstrumentRequestsTest::test_requests_instrumentation_via_prepared_request
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/cookiejar.py:1597: UserWarning: http.cookiejar bug!
Traceback (most recent call last):
File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/cookiejar.py", line 1595, in make_cookies
split_header_words(rfc2965_hdrs), request)
File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/cookiejar.py", line 384, in split_header_words
for text in header_values:
TypeError: 'Mock' object is not iterable
=> use urllib3-mock instead of our (very limited) self-built mock

elasticapm/base.py, elasticapm/contrib/flask/__init__.py, elasticapm/events.py
this removes the long-deprecated camelCased API methods, as well as the `Query` event type, which AFAIK we never really supported.
=> removed Query event and camelCased client API methods

elasticapm/base.py, elasticapm/traces.py, tests/instrumentation/transactions_store_tests.py
To tag a transaction, the user only has to import `elasticapm`, then call
`elasticapm.tag(tag1=value1, tag2=value2)`:
import elasticapm
elasticapm.tag(foo='bar')
This is an alternative API to PR #27. It's IMO a nicer API, but due to the key being a keyword argument, it has stricter rules than what we enforce in the APM server (e.g. it can't have any whitespace).
=> added tagging functionality (alternative API)

elasticapm/base.py, tests/client/client_tests.py
This caused a validation error because we'd add an otherwise empty `log`
object to the exception.
=> never gather log stack trace for exceptions

elasticapm/transport/http_urllib3.py
This ensures that `response.read()` returns the response content.
Unfortunately, we can't really test this with urllib3-mock, since it
doesn't implement this behavior.
=> make sure that content isn't preloaded in the urllib3 response

elasticapm/transport/http_urllib3.py, tests/transports/test_urllib3.py
But not in Python 3, that would be too easy.
=> turns out that in Python2, the URL _also_ has to be binary.

scripts/build_docs.sh
By default all headlines with level 2 (`==`) will get its own page.
When setting `--chunk=1`, all headlines with level 3 (`===`) will get its own page as well and will be shown in the ToC like so:
=> Ensure docs are build locally just as they are in prod

CHANGES.md, docs/configuration.asciidoc, docs/django.asciidoc, elasticapm/base.py, elasticapm/conf/__init__.py, elasticapm/conf/defaults.py, elasticapm/contrib/django/client.py, elasticapm/contrib/django/management/commands/elasticapm.py, elasticapm/contrib/pylons/__init__.py, tests/asyncio/test_asyncio_client.py, tests/client/client_tests.py, tests/config/tests.py, tests/contrib/django/django_tests.py, tests/contrib/pylons/tests.py
Also removed logic that would send events to multiple servers
=> turned `servers` list setting into single `server` string setting

README.rst
The Elastic company isn't called `Elastic, Inc.` so I took the liberty to clean this up - hope it's ok 😅 If we wanted to call it by the legal name it should be `Elasticsearch BV`, but I don't see the benefit of that in a line like this
=> Remove Inc from Elastic name in README

docs/configuration.asciidoc
the real name for option used by code is span_frames_min_duration, not span_frames_min_duration_ms
=> fix span_frames_min_duration config option name

tests/scripts/download_json_schema.sh
The removed files are:
- `meta.json`
- `schema.json`
I also changed tabs to spaces as you used a combination of both in the same file. So now it's aligned. I hope that was ok?
=> test: remove deleted APM Server JSON schema files

tests/scripts/download_json_schema.sh
Previously it would just write the error message inside the file it was trying to download.
This makes the tests fail if curl encounters an error as opposed to silently continue.
~~This PR should therefore fail until #215 have been merged and this PR have been rebased.~~ update: rebased
=> test: make curl fail if it can't download the APM Server schemas

docs/api.asciidoc, docs/index.asciidoc
Use the shared attributes provided
by elastic/docs for linking to other
product docs, forums, etc.
=> docs: use shared attributes

tests/docker-compose.yml
For details, see: https://github.com/elastic/apm-agent-python/pull/205#discussion_r200806206
=> test: prefix database volume on Jenkins with 'py'

tests/scripts/download_json_schema.sh
Some times curl fails when trying to download a schema from GitHub. This is usually just a temporary error and will succeed if retried.
This commit retries downloads up to 5 times before failing permanently.
=> test: make schema integration tests more resilient

README.rst
=> docs: add link to custom integration example

elasticapm/handlers/logbook.py, elasticapm/handlers/logging.py, tests/handlers/logbook/logbook_tests.py, tests/handlers/logging/logging_tests.py
Update LoggingHandler so that it converts the log record
message to a string. The message may be any arbitrary object,
and currently non-string messages are being sent as objects,
which the APM Server rejects.
Fixes #295
=> Update LoggingHandler to stringify record.msg

docs/advanced-topics.asciidoc, docs/getting-started.asciidoc, docs/index.asciidoc
* Updated `index.asciidoc` to move `getting-started` and `advanced-topics` into their own files. 
* Updated agent `getting-started.asciidoc` per elastic/apm-dev#387
* Added bullet point links to address blank white space in `advanced-topics` (see below)
=> docs: update getting-started and file structure

docs/api.asciidoc, docs/index.asciidoc
Improves cross document linking per https://github.com/elastic/apm/issues/19
=> Docs: version links (2x)

docs/api.asciidoc, docs/getting-started.asciidoc, docs/index.asciidoc
Improves cross document linking per https://github.com/elastic/apm/issues/19
=> docs: version links (master)

elasticapm/instrumentation/packages/urllib3.py, elasticapm/utils/disttracing.py, tests/utils/test_disttracing_header.py
The value of `TRACEPARENT_HEADER_NAME` is set as a byte string. This causes the header dict in `requests` to have mixed string and byte values on Python 3. The expected behaviour is for both keys and values to be native strings, that is the `str` type for both Python 2 and 3.
This behaviour causes our application to crash due to us doing `json.dumps` on `request.headers`:
`TypeError: Object of type bytes is not JSON serializable`
```python
{
"Accept": '*/*',
"Accept-Encoding": 'gzip, deflate',
"Authorization": 'Filtered',
"Connection": 'keep-alive',
"elastic-apm-traceparent": b'00-706eb5e0137e6d165e10d964b00ea43c-70016c1f38b65b27-01',
"User-Agent": 'python-requests/2.19.1'
}
```
=> Use native string for disttracing header

Jenkinsfile, tests/scripts/docker/run_tests.sh
* This code was a test to generate a changelog between two commits and show the info in the log of the job, it is not needed and breaks the build on the master branch because CHANGE_TARGET is only defined on PRs.
* Do not use PIP_CACHE environment variable on run_test.sh, it breaks the old CI, the path value in the old job is relative, it should be absolute.
=> [APM-CI] remove changelog generation from logs

Jenkinsfile, scripts/jenkins/docs.sh
* avoid having to change the Jenkinsfile every time we set a pipeline shared library as a stable version to use.
* Use buildDocs pipeline step to build docs
* limit max PR builds per hour to 60
* set quiet period to 10 seconds
=> [APM-CI] use current as pipeline shared library version

docs/index.asciidoc
Fixes https://github.com/elastic/apm-agent-python/issues/423
Also moves the note about where to read the docs to the top of the page instead of in the middle.
=> [docs][1.x] Fix external note and links

docs/index.asciidoc, docs/release-notes.asciidoc
See elastic/apm#68.
Adds a link to release notes.
=> [docs] Add release-notes page

elasticapm/context/__init__.py, elasticapm/traces.py, tests/context/__init__.py, tests/context/test_context.py
Re-PR of #453 
* Extract out logic to decide which backing to use for execution_context
into a function init_execution_context
* Check if gevent or eventlet has monkey patched _threading.local, if it
has then use elasticapm.context.threadlocal as the backing.
=> Execution context - use thread locals if gevent/eventlet has monkey patched it

Jenkinsfile
- It will enable to use the integrations tests either from pull requests which are coming from a forked repo or from this one.
=> ci(jenkins): enable pull requests using the upstream repo

.ci/jobs/apm-agent-python-downstream.yml
* ignore SCM triggers on the downstream job
* do not scan PRs on the downstream job
=> ci: ignore SCM triggers on downstream job

Jenkinsfile
user error step, allow empty junit results
=> fix: user error step, allow empty junit results

.ci/Jenkinsfile, Jenkinsfile
Since the documentation team has elastic-ci/docs build in place for all our PRs, our Documentation stage lose sense, we are doing the same and we have to maintain it. Because of that, we will start to remove this stage from all projects.
=> ci: remove the documentation stage

.ci/Jenkinsfile, .pre-commit-config.yaml, Jenkinsfile, docs/run-tests-locally.asciidoc
- Use `pre-commit` as the single source of truth.
- Enable `pre-commit` stage in the CI pipeline.
- Enable GitHub check 
- Update docs.
- Fix .pre-commit.yml file `(<unknown>): found unknown escape character while parsing a quoted scalar at line 27 column 18`
- Test output for the pre-commit lint rules in JUnit format.
=> ci: enable pre-commit stage within the Jenkins pipeline

.ci/Jenkinsfile, Jenkinsfile
The current when implementation for the release stage in the CI uses `GLOB` rather than `REGEX` refers to:
- https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/b257a9e40fac92c9880d438a9be787f9a8d23ed8/pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TagConditional.java#L83
and [docs](https://jenkins.io/doc/book/pipeline/syntax/#when) see tag section in the [when docs](https://jenkins.io/doc/book/pipeline/syntax/#when) page.
```
The optional parameter comparator may be added after an attribute to specify how any patterns are evaluated for a match: EQUALS for a simple string comparison, GLOB (the default) for an ANT style path glob (same as for example changeset), or REGEXP for regular expression matching. For example: when { …
```
=> ci: fix tag pattern to be REGEX based and less restrictive

.ci/Jenkinsfile, .ci/jobs/apm-agent-python-linting-mbp.yml, .ci/jobs/apm-agent-python-mbp.yml, .ci/linting.groovy, Jenkinsfile
- The main pipeline has been split into two `pipelines`.
- The main pipeline will evaluate the `sanity check` stage in the branches only.
- The new pipeline will run the `sanity-check` for the PRs only.
- The new pipeline will create a new GitHub check called `apm-ci/linting/pr-merge`
@beniwohli, not sure whether this approach could help to get some quick feedback independently whether the PRs are coming from someone with write privileges in this repo or a contributor.
=> ci(jenkins): decouple linting from the main CI pipeline

.ci/linting.groovy
- This pipeline does not use the gitCheckout step anymore as it does only care of the linting so not further requirements to skip the build
=> fix: it does not use the gitCheckout step anymore

docs/index.asciidoc
* Updates `4.x` documentation to no longer point to current. It will forever point to APM Server / ES/ Kib `7.3`.
* Removes a very old/unused `server-branch` attribute
=> docs: update branch for 4.x

.ci/Jenkinsfile, .ci/linting.groovy
- preCommit step provides support to the dockerImage requirement.
- Docker login is not required for this particular sanity checks.
- Docker login does not work within the context of the docker.image.
=> ci(jenkins): delegate docker setup to the preCommit step

.ci/Jenkinsfile, .ci/linting.groovy, Jenkinsfile
Reverts elastic/apm-agent-python#557
I'm afraid the proposed approach seems to be quite problematic when running the pre-commit-venv internals. So let's keep it as it was.
For the record I managed to reproduce the same issue locally running docker:
```
docker run --rm -ti -u "$(id -u):$(id -g)" -e PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$(pwd)/bin -v $(pwd):$(pwd):rw,z python:3.7-stretch /bin/bash
I have no name!@5a742775abbd:~$ HOME=/Users/vmartinez/work/src/github.com/elastic/apm-agent-python
I have no name!@5a742775abbd:~$ PATH=$PATH:$HOME/bin
...
I have no name!@5a742775abbd:~$ env
LANG=C.UTF-8
HOSTNAME=5a742775abbd
OLDPWD=/
GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
PWD=/Users/vmartinez/work/src/github.com/elastic/apm-agent-python …
```
=> Revert "ci(jenkins): delegate docker setup to the preCommit step"

README.rst
fix leftover when transitioned from `travis-ci` to `apm-ci.elastic.co`
=> chore: update build URL and build status icon

.ci/Jenkinsfile, .ci/downstreamTests.groovy, .ci/linting.groovy, Jenkinsfile
- When working with ephemeral workers the only agent which might be always up is the `master` one, besides the static workers if any. So far, we don't have any after moving to windows ephemeral workers.
- This will help to avoid overloading the master, although might consume another worker which will be active from the very beginning of the pipeline until the very end as the post step happens at the `stages` level.
- This particular change will help to scale up when the build queue is long but will increase a bit the wait time.
- In other words, there are three major concepts regarding the overall time:
- Waste of time for resources during the build
- Waste of time for resources in the queue
- Real build time.
- This particular fix will increase the time for the first one but will reduce …
=> ci(jenkins): avoid using the any agent to skip running in the master-worker

.ci/Jenkinsfile, Jenkinsfile
- https://github.com/elastic/apm-agent-python/pull/568 caused a regression as the env variable is defined at the worker level.
- `@Field` helps to create global variables, therefore `gitCommit` is the new variable which does substitute the environment variable.
- Avoid using a worker for running the tests, and reuse the top-level one
- GIT_SHA rather than GIT_BASE_COMMIT as the last one is caused when doing a merge within a PR.
=> ci(jenkins): the environment GIT_BASE_COMMIT is not accessible

.ci/Jenkinsfile, .ci/downstreamTests.groovy, .ci/linting.groovy, Jenkinsfile
This reverts https://github.com/elastic/apm-agent-python/pull/569 and https://github.com/elastic/apm-agent-python/pull/568
- As long as we use the share step `gitCheckout` we might need to use the agent top-level to share the env variables between stages.
- It's not ideal but even though the changes were quite straight, its behavior was not as expected. 
- Let's keep the pipeline stable for now and we will figure out what's going on.
=> ci(jenkins): revert none agent

CHANGELOG.md, elasticapm/transport/http.py, tests/transports/test_urllib3.py
Given an http:// server url and `'VERIFY_SERVER_CERT': False`,
don't pass in assert_hostname (it will error).
Fixes #570
=> Fix to only add assert_hostname for https urls

.ci/.jenkins_exclude.yml, .ci/.jenkins_framework.yml, .ci/.jenkins_framework_full.yml, CHANGELOG.md, setup.py, tests/contrib/zerorpc/zeropc_tests.py, tests/requirements/requirements-base.txt, tests/requirements/requirements-zerorpc-0.4.txt, tests/scripts/envs/zerorpc.sh
zerorpc tests are currently being skipped all of the time because of an incorrect gevent version specified. The line `zerorpc = pytest.importorskip("zerorpc")` actually raises an `ImportError` on it's dependency `gevent`, NOT on `zerorpc` itself:
```
___________________________________________ ERROR collecting tests/contrib/zerorpc/zeropc_tests.py ___________________________________________
ImportError while importing test module '/app/tests/contrib/zerorpc/zeropc_tests.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python2.7/site-packages/six.py:709: in exec_
exec("""exec _code_ in _globs_, _locs_""")
tests/contrib/zerorpc/zeropc_tests.py:40: in <module>
import zerorpc
/usr/local/lib/python2.7/site-packages/zerorpc/__init__.py:28: in …
```
=> Fix zerorpc tests, move them to separate test env

.ci/downstreamTests.groovy
* Shallow cloning with a mergeTarget causes the refusing to merge unrelated histories issue.
* Avoid shallow cloning then.
=> ci(jenkins): disable shallow clone

CHANGELOG.md, elasticapm/instrumentation/packages/psycopg2.py, tests/instrumentation/psycopg2_tests.py
this ensures that the connection/cursor used in the context manager are
wrapped instances
fixes #577
=> add wrappers for psycopg2's connection/cursor context managers

.ci/jobs/apm-agent-python-downstream.yml, .ci/jobs/apm-agent-python-mbp.yml, .ci/jobs/apm-agent-python-mbp0.yml
it will replace the generic context `continuous-integration/jenkins/*` for a fixed one that points to the name of the instance that generates the context `apm-ci`, it is important when we have multiple multibranch jobs listening on a repo to avoid to overwrite contexts.
**Now**
**After**
=> ci(jenkins): Set GitHub notification context to apm-ci

.ci/.jenkins_exclude.yml, .ci/.jenkins_framework.yml, .ci/.jenkins_framework_full.yml, tests/context/eventlet_threading_tests.py, tests/context/gevent_threading_tests.py, tests/requirements/requirements-base.txt, tests/requirements/requirements-gevent-newest.txt, tests/scripts/envs/gevent.sh
Typo in call to `is_object_patched`. Correct module to check is `threading`, not `_threading` - https://docs.python.org/3/library/threading.html#threading.local
=> Execution context - correctly check if gevent has patched threading.local

.gitignore, docs/run-tests-locally.asciidoc, tests/client/client_tests.py, tests/requirements/requirements-base.txt, tests/scripts/download_json_schema.sh
* Need to use `gtar` on macOS to get `--wildcard` support for `make json schema`
* ~Add psutil to requirement-base.txt for `test_send_remote_failover_sync_non_transport_exception_error`~
* Turns I just needed to fix the test properly, by disabling `metrics_sets` for that test.
* Update .gitignore with a couple of testing artifacts
* Fix a documentation bug around syntax for `tests/scripts/docker/run_tests.sh`
* Add a note about apm-integration-testing
=> Test setup and documentation fixes

.ci/linting.groovy
- `jenkins run the linters` or `jenkins run linters` rather than `jenkins run lint`
=> ci(jenkins): change the github comment for the linters

tests/client/client_tests.py, tests/contrib/django/django_tests.py, tests/contrib/flask/flask_tests.py
These two config options are slated for remote config in the next stack release.
see https://github.com/elastic/apm/issues/138#issuecomment-530713975
=> add tests to check update-ability of transaction_max_spans and capture_body

CHANGELOG.md, docs/advanced-topics.asciidoc, docs/api.asciidoc, docs/configuration.asciidoc, docs/logging.asciidoc, elasticapm/__init__.py, elasticapm/base.py, elasticapm/conf/__init__.py, elasticapm/handlers/logging.py, elasticapm/handlers/structlog.py, elasticapm/traces.py, tests/handlers/logging/logging_tests.py
* Added new entries to the public API as helpers to retrieve transaction, trace, and span IDs
* Added new ways to add APM tracing fields to logs:
* `logging` filter
* `structlog` processor
* automatic log_record_factory for python 3.2+
* Added new "Logging Integrations" documentation
* Added documentation around ingest for log correlation
* Added tests for the filter, processor, and log_record_factory
Resolves elastic/apm-agent-python#520
=> Add logging integrations with logging and structlog

docs/index.asciidoc
This PR unblocks https://github.com/elastic/docs/pull/1170. Because Agents are verisioned separately from the stack, this attribute needs to be defined locally in each Agent.
Backport to `5.x`.
=> [docs] Add ECS versioning

docs/index.asciidoc
Backports the following commits:
* docs: fix ECS versioning (#593)
=> [docs][5.x] fix ECS versioning (#593)

docs/advanced-topics.asciidoc, docs/logging.asciidoc, elasticapm/handlers/logging.py, tests/handlers/logging/logging_tests.py
We need a custom Formatter class in order to add error handling for
any logs which happen before the Client is initialized (and our
LogRecordFactory is put into place).
This also fixes a typo in the format string in the previous documentation (missing trailing `s` on our elasticapm additions). (@bmorelli25 FYI, since I know you're writing centralized documentation based on the old, invalid format string)
Ref #586
=> Add logging Formatter class

elasticapm/events.py, tests/events/tests.py
Ref #599
`sys.exc_info()` returns `(None, None, None)` if there is no active
exception. Still fail hard and fast, but more clearly.
=> Fix Exception.capture error handling

.ci/Jenkinsfile, .ci/downstreamTests.groovy, .ci/linting.groovy, Jenkinsfile
- Let's reuse the top-level agent to reduce the number of fo requested agents and speed up just a bit the builds.
- Reset labels to be `linux && immutable` to help with what kind of OS is required to be used.
- Overall time improvements from 4.30m to 3m until the test stage. 
- Release
- Validate the `pre-commit` docker doesn't leave any leftovers
=> ci(jenkins): reuse agents (4 less agents to be used)

tests/client/client_tests.py, tests/instrumentation/transactions_store_tests.py
this avoids flakiness in tests due to high CPU usage on the test instance
=> use duration argument instead of time.sleep in tests

CHANGELOG.md, elasticapm/instrumentation/packages/psycopg2.py, elasticapm/instrumentation/register.py, tests/instrumentation/psycopg2_tests.py
psycopg2 2.8 added two new extensions, `quote_ident` and
`encrypt_password`. Both extensions do a type check on the
connection/cursor object, which fails if they are wrapped with our
object proxies. Similar to `register_type`, we need to unwrap the
connection/cursor before handing it to these extensions.
fixes #620
=> unwrap pg connection/cursor for new psycopg2 extensions

CHANGELOG.md, elasticapm/utils/cgroup.py, tests/utils/cgroup_tests.py
When the systemd cgroup driver is used, cgroup paths will have hyphens (e.g. in pod UIDs) escaped to underscores. When we're parsing cgroups, we must therefore unescape them.
refs elastic/apm#165
=> fix pod ID for kubernetes when using the systemd cgroup driver

.ci/downstreamTests.groovy
Enable th build rotation of up to 100 builds for the downstream jobs 
Hard to debug what's going on when a build error happens and the build rotation was applied
closes #ISSUE
=> ci(jenkins): downstream@master log rotation didn't keep too many builds in the history

CHANGELOG.md, elasticapm/contrib/flask/__init__.py, tests/contrib/flask/flask_tests.py
The `request_finished` signal isn't sent if an unhandled exception
occurs, and other signals (e.g. `request_teardown` don't provide the
`response` object.
As a workaround, we close the transaction in the exception handler.
This requires us to move some logic into the `request_started` handler
to ensure it is run.
Unfortunately, this means we don't have any response context data,
as the response isn't created yet when the exception handler is called.
So far, no transaction at all is captured when an error occurs. While
this solution isn't perfect, it gets us pretty close without having
to resort to wrapping/patching Flask APIs.
closes #629
=> flask: close the transaction in the exception handler

CHANGELOG.asciidoc, tests/utils/tests.py
also, use proper parametrization for test_get_url_dict test cases
Adds changelog entry for #649, and uses parametrization for the related
test.
With parametrization, all test cases are run independently. That means
that if one of the cases fails, the other cases will still be run.
=> update changelog for #649

.gitignore, .pre-commit-config.yaml, Jenkinsfile, scripts/run-benchmarks.sh
* Run benchmark by default for each commit into the master branch. It does enable us to run the benchmark on a PR basis but only if using the Jenkins UI. 
* Besides, it does enable us to customize what CI stages should be launch using the UI. 
APM agents do run benchmark by default.
- See [build without tag flag and as-is](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/PR-651/15/pipeline)
- See [build with latest changes](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/PR-651/20/)
=> ci(jenkins): enable benchmark run

tests/metrics/cpu_psutil_tests.py
skip flaky metrics comparison test
Unfortunately, this test fails quite often on CI due to unpredictable
load.
=> skip flaky metrics comparison test

setup.py
Adds some new entries in our trove classifiers
These entries are used by e.g. pypi.org to show meta data about the
package.
=> updated trove classifiers to include Python 3.7 and 3.8, and license

scripts/run-benchmarks.sh
tags benchmark runs triggered by CI with mode=CI
We backfilled benchmarks for all commits since v4.0, and tagged
them with mode=backfill. Using this, we can tell if a benchmark
has been triggered by CI or not.
=> add tag "mode" to indicate that a benchmark has been triggered by CI

.appveyor.yml, Makefile, docs/api.asciidoc, docs/custom-instrumentation.asciidoc, elasticapm/contrib/asyncio/__init__.py, elasticapm/contrib/asyncio/traces.py, elasticapm/instrumentation/packages/asyncio/__init__.py, elasticapm/instrumentation/packages/asyncio/base.py, elasticapm/instrumentation/packages/asyncio/sleep.py, elasticapm/instrumentation/register.py, elasticapm/traces.py, setup.cfg, tests/instrumentation/asyncio/__init__.py, tests/instrumentation/asyncio/base_tests.py
It adds a new API, `async_capture_span`, which can be used to decorate
coroutines and asynchronous context managers (`async with`).
Additionally, it adds instrumentation for `asyncio.tasks.sleep`.
Providing these APIs allows ourselves and our users to instrument
asynchronous applications.
refs #598
=> added async_capture_span for decorating coroutines and `async with`

CHANGELOG.asciidoc, docs/configuration.asciidoc, elasticapm/conf/__init__.py, elasticapm/conf/constants.py, elasticapm/contrib/django/apps.py, elasticapm/contrib/flask/__init__.py, elasticapm/contrib/opentracing/tracer.py, elasticapm/instrumentation/packages/urllib.py, elasticapm/instrumentation/packages/urllib3.py, elasticapm/utils/disttracing.py, tests/contrib/django/django_tests.py, tests/contrib/flask/flask_tests.py, tests/contrib/opentracing/tests.py, tests/instrumentation/urllib3_tests.py, tests/instrumentation/urllib_tests.py
On incoming requests, we first check for the presence of `traceparent`,
and fall back to `elastic-apm-traceparent`.
For outgoing requests, `traceparent` is always set. `elastic-apm-traceparent`
is set if the config option `use_elastic_traceparent_header` is set to
True. For now, this option defaults to True, but will be changed to False
after a grace period.
TraceContext is now a recommendation candidate, time to support it
fully.
closes #628
refs elastic/apm#71
=> Implement Trace Context standard

.ci/.jenkins_framework.yml, .ci/.jenkins_framework_full.yml, conftest.py, setup.cfg, tests/contrib/celery/django_tests.py, tests/contrib/celery/flask_tests.py, tests/contrib/django/conftest.py, tests/contrib/django/django_tests.py, tests/contrib/flask/flask_tests.py, tests/instrumentation/django_tests/conftest.py, tests/instrumentation/django_tests/template_tests.py, tests/requirements/requirements-none.txt, tests/scripts/envs/django.sh, tests/scripts/envs/flask.sh, tests/utils/compat_tests.py
also, use fixtures as pytest plugins instead of importing them
It uses pytest's ability to pick up folder-specific conftests.
This allows us to move django-specific setup to where it belongs.
Currently, when running the django/flask matrix builds,
all non-specific tests (as in, anything that doesn't have
any specific marks) also runs. This leads to a lot of repeated
tests.
Ideally, we'd introduce new marks for Django/Flask, and a new
matrix row that only runs non-marked tests.
Having the conftest separate is the first step for this.
=> move django specific stuff in conftest to subdirectory

.ci/.jenkins_exclude.yml, .ci/.jenkins_framework_full.yml, docs/supported-technologies.asciidoc, tests/requirements/requirements-psycopg2-2.5.txt, tests/requirements/requirements-psycopg2-2.6.txt, tests/requirements/requirements-psycopg2-2.7.txt, tests/requirements/requirements-psycopg2-newest.txt
Removes old psycopg2 versions from full matrix test builds, and
ensures that both 2.7 and 2.8 are tested.
Testing of these versions broke some time between June and now, due
to our Python containers being upgraded to a version that doesn't use
such old postgres client libraries anymore. Continuing to test these
would be exceedingly difficult, and not worth the hassle.
=> remove testing for psycopg2 2.5 (released in 2013) and 2.6 (2016)

elasticapm/contrib/aiohttp/middleware.py, tests/requirements/requirements-aiohttp-3.0.txt
Older 3.x versions than 3.0.6 had some attributes missing in TCPSite.__slots__,
so that's the minimum we can test with.
Resource.canonical has been added in 3.3, so we need to fall back to private
attributes for older versions.
=> fix issues with older versions of aiohttp

.ci/.jenkins_exclude.yml
Excludes psycopg2-2.7/python-3.8 combination
psycopg2 has an incompatibility with Python 3.8. It has been
fixed for psycopg2 2.8, but not for 2.7 and earlier.
See https://github.com/psycopg/psycopg2/issues/858
=> exclude psycopg2-2.7/python-3.8 due to build issues

scripts/build_docs.sh
Adds `--direct_html` flag to the doc build script. See https://github.com/elastic/docs/pull/1636 for more info.
=> [docs] add direct_html flag

.ci/jobs/apm-agent-python-linting-mbp.yml, .ci/jobs/apm-agent-python-mbp.yml, .ci/jobs/apm-agent-python-nightly-mbp.yml
Adds reference repos.
These correspond to repos and download locations which can be seen in [the Jenkins job which mirrors them](https://apm-ci.elastic.co/job/jenkins-git-fetch-reference/).
Makes for more efficient git checkouts.
=> Add git reference repos to CI configuration

.ci/linting.groovy, .ci/nightly.groovy, Jenkinsfile
Tidy up the existing env variables, which are now defined in the preCommit step context or could be defined once and used in several places
Simplify the pipeline
https://github.com/elastic/apm-pipeline-library/pull/325
=> ci(jenkins): tidy up env variables

elasticapm/base.py, tests/client/client_tests.py
We currently ignore the hostname configuration in the
system info collection. That's no good.
Thanks to @esseti for finding the bug and suggesting a fix!
fixes #688
=> use the configured hostname in get_system_info

.flake8
Adds BLK100 to ignorable errors from flake8. We already run black 
in its own pre-commit hook and on CI, so no need to also have 
flake8/hound run black.
=> ignore errors from flake8-black

CHANGELOG.asciidoc, docs/supported-technologies.asciidoc, elasticapm/instrumentation/packages/elasticsearch.py, tests/instrumentation/elasticsearch_tests.py
Fixes elasticsearch tests (failing as of the release of 7.5.1), and removes some brittleness around argument ordering, since that API is dynamically generated and order is not guaranteed.
Also removed our extensive matrix tracking the position of the `body` argument. `elasticsearch-py` [actually doesn't support non-kwarg use of the API](https://elasticsearch-py.readthedocs.io/en/master/api.html#api-documentation), they are only args because there's no way in py2 to have a required kwarg. Made a note in the docs and updated the tests to match.
=> Fix elasticsearch tests

.ci/packer_cache.sh, tests/scripts/docker/docker_build.sh, tests/scripts/docker/run_tests.sh
Use the just built docker images from [pipeline](https://apm-ci.elastic.co/job/apm-shared/job/apm-docker-images-pipeline/) that are already available in the internal docker registry and retag them to use them in the CI pipeline.
Speed up the CI overall execution time
```bash
hub checkout pr 701
sh -x .ci/packer_cache.sh
```
_NOTE_: `/usr/local/bin/bash_standard_lib.sh` is required to exist. That particular requirement is already in place for the CI workers.
superseed #700
=> Enable docker image cache in the CI workers

setup.py
Technically we support 3.4 until one more minor version, but
I'm only doing this so that our badge on the README will read
correctly, so jumping the gun a little should be fine.
=> Update supported python versions

docs/advanced-topics.asciidoc
Happened to notice this missing link. The include was there, but not the link!
=> Fix missing link in docs

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/base.py, setup.py, tests/instrumentation/base_tests.py
To achieve this, we use our own FunctionWrapper subclass,
and check if the callable is already of that type.
This only works if we are the only module that wraps the
original function. If other providers are also wrapping
the callable, we might miss it.
It might be possible in certain cases that a module
is instrumented twice. 
Fixes #695
=> avoid double instrumentation of callables

CONTRIBUTING.md
Small update that hopefully makes the docs release process more clear.
=> [docs] Update docs release process

CHANGELOG.md, CONTRIBUTING.md, docs/upgrading.asciidoc
This PR defines end of life and end of maintenance dates for the Python Agent.
We love all our products, but sometimes we must say goodbye to a release so that we can continue moving forward on future development and innovation.
For https://github.com/elastic/apm/issues/173.
=> [docs] Add EOL table to documentation

Jenkinsfile, tests/scripts/docker/docker-get-logs.sh, tests/scripts/docker/docker-summary.sh, tests/scripts/docker/run_tests.sh
It grabs the Docker containers logs before to destroy the containers.
In order to diagnose some issues sometimes, we need the Docker container logs.
related to https://github.com/elastic/apm-agent-python/issues/718
=> ci: grab Docker containers logs

elasticapm/base.py
turns out PID is set to None in the beginning,
leading to a crash when logging this message.
=> use %r instead of %d to log PID change

elasticapm/contrib/celery/__init__.py, tests/fixtures.py
Removes a now invalid method call
Because we shouldn't break celery :)
closes #723
=> during the threading refactor, this call went forgotten

.ci/.jenkins_exclude.yml
This was causing test failures due to psutil 5.7.0 being released.
See https://github.com/giampaolo/psutil/issues/1659
We can remove this exclusion once the next version of pypy2 is released.
=> Add psutil to pypy-2 exclusions

Jenkinsfile
Replace credentials
No more credentials to the old cluster
closes #ISSUE
=> ci(jenkins): use the cloud benchmark cluster

tests/requirements/requirements-psutil-4.0.txt, tests/requirements/requirements-psutil-5.0.txt
Previously, due to no upper constraint, all 3 psutil matrix builds
ran using the newest version, which kinda defeats the purpose of
matrix tests.
=> fix psutil requirements files to have upper limits

scripts/install-python.ps1
Install python with the version that's the same that the given VERSION or the closest one. Therefore the VERSION format could be:
- fully
- major
- major.minor
- semver...
It will help to install python3 in windows just given the major.minor version rather than the major.minor.patch version
Caused by https://github.com/elastic/apm-agent-python/pull/726
```powershell
$Env:VERSION = "3.8"
.\install-python.ps1
```
=> ci(jenkins): install python3 for the given VERSION

Jenkinsfile
Get rid of the sendData to ES for the downstream jobs.
We have changed our process to send data to ES, and the legacy approach is now deprecated.
closes #ISSUE
=> ci(jenkins): send downstream build data to ES is not required anymore

codecov.yml
The CodeCov stats have been broken, throwing false negatives, for
months. Let's disable them until we can figure out how to make them
accurate/useful.
=> Disable codecov

elasticapm/instrumentation/packages/asyncio/aiohttp_client.py, tests/instrumentation/asyncio/aiohttp_client_tests.py
Fix for broken `aiohttp.client` tracker.
`url` may be not a string:
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L1083
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/typedefs.py#L45
=> Fix aiohttp client

Jenkinsfile
Enable PATH for the benchmarking stage
Caused by https://github.com/elastic/apm-agent-python/commit/57f5dec04736e9a0bd7615253f82f54ce9005cf0#diff-58231b16fdee45a03a4ee3cf94a9f2c3L27
closes #ISSUE
=> ci(jenkins): fix benchmark PATH variable

.gitignore, docs/index.asciidoc, docs/troubleshooting.asciidoc
It struck me yesterday when I was helping out with a [discuss post](https://discuss.elastic.co/t/python-apm-agent-for-flask-doesnt-report-metrics/223083) that we don't really have a central place to send people for troubleshooting.
I'd love feedback on the relevance of each of these additions, as well as their content and order. It doesn't flow very well as a doc, but I'm not sure how to make it better since it's a hodge-podge list of tips.
=> Add troubleshooting docs

Jenkinsfile
It changes the name of the parent stage Release to Prepare Release.
It is a cosmetic change to avoid confusion.
=> chore: rename parent stage Release

elasticapm/instrumentation/packages/cassandra.py
Running the full matrix, an issue with old versions of cassandra
was revealed. This should fix the issue
=> fixed destination issue with old versions of cassandra-driver (<3.18)

tests/instrumentation/asyncio/elasticsearch_async_client_tests.py, tests/instrumentation/elasticsearch_tests.py
Fixes some test failures due to the release of Elasticsearch client 7.6.0
=> Update tests for Elasticsearch client 7.6.0

elasticapm/contrib/starlette/utils.py, tests/contrib/asyncio/starlette_tests.py
Fix Starlette request body collection for missing content-type header.
Sorry for the noise from `black`. Not sure how it wasn't run on these files previously..... Might be worth investigation.
=> Fix error with missing content-type header in Starlette

.ci/jobs/apm-agent-python-nightly-mbp.yml, Jenkinsfile
- Run nightly builds on a nightly basis.
- Enable full test matrix if comment `jenkins run the full tests`
closes #ISSUE
https://github.com/elastic/apm-agent-python/pull/767#issuecomment-601808655 caused [build #3](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/PR-767/3/pipeline)
=> ci(jenkins): run full test matrix on a PR basis if comment

docs/getting-started.asciidoc
This PR adds a link to the Agent/Server compatibility matrix.
For https://github.com/elastic/apm/issues/229.
=> docs: Add link to Agent/Server compatibility

Jenkinsfile
building packages currently fails due to https://github.com/pypa/manylinux/issues/512
=> temporarily disable building packages

docs/configuration.asciidoc, elasticapm/base.py, elasticapm/conf/__init__.py, elasticapm/traces.py, elasticapm/transport/base.py, tests/client/client_tests.py, tests/contrib/django/django_tests.py, tests/contrib/flask/flask_tests.py, tests/transports/test_base.py
This PR tests support for the remote config options being added in Kibana for 7.7. (All config options technically support remote config, but we need to test that propagation works properly.)
List:
I'll be opening a separate PR for `enabled`/`recorded` once I get to those, since they're not as urgent (and will require more work).
Refs https://github.com/elastic/apm/issues/213
=> Remote config options for 7.7

elasticapm/transport/http.py, tests/fixtures.py, tests/transports/test_urllib3.py
Due to an oversight, we were sending the wrong headers for remote config requests. It doesn't seem to bother apm-server so far, but let's better be on the safe side.
=> send the correct content-type and no content-encoding for remote config

elasticapm/conf/__init__.py, elasticapm/contrib/aiohttp/middleware.py, elasticapm/contrib/aiohttp/utils.py, elasticapm/contrib/django/client.py, elasticapm/contrib/django/middleware/__init__.py, elasticapm/contrib/flask/__init__.py, elasticapm/contrib/flask/utils.py, elasticapm/contrib/starlette/__init__.py, elasticapm/contrib/starlette/utils.py, elasticapm/contrib/tornado/utils.py, elasticapm/instrumentation/packages/tornado.py, tests/config/tests.py, tests/contrib/asyncio/aiohttp_web_tests.py, tests/contrib/asyncio/starlette_tests.py, tests/contrib/asyncio/tornado/tornado_tests.py, tests/contrib/django/django_tests.py, tests/contrib/flask/flask_tests.py
This refactors a bit how the different `get_data_from_request/response` functions work, taking a `Config` instance as an argument, instead of direct `capture_body` / `capture_headers` values.
It also adds tests for all the different frameworks
=> Capture headers body dynamic all frameworks

elasticapm/contrib/flask/__init__.py
Fixes the following warning on Python 3.8
```
/srv/brm-api_staging/venv/lib/python3.8/site-packages/elasticapm/contrib/flask/__init__.py:136: SyntaxWarning: "is" with a literal. Did you mean "=="?
if self.logging or self.logging is 0:  # noqa F632
```
=> Fix SyntaxWarning on Python 3.8

elasticapm/contrib/aiohttp/middleware.py, elasticapm/contrib/aiohttp/utils.py
The not-yet-released aiohttp 4.0 changes a bit how HTTP exceptions
work. They are no longer inheriting from Response.
=> fix handling of responses with aiohttp4

elasticapm/utils/__init__.py, tests/utils/tests.py
Adds error handling around urlparse port access. If the port doesn't cast to an `int` then a ValueError will be raised. We want to suppress that error so we're a good citizen in the app.
Closes #798
=> Add error handling around urlparse ports

.ci/.jenkins_exclude.yml
This started throwing an error due to an upstream change and if I'm being honest I'm too lazy to try to track down why these two edge technologies are failing.
=> Disable pypy-3 pymssql-newest

CHANGELOG.asciidoc, elasticapm/metrics/base_metrics.py
Use a copy for iterating over metrics during collection.
This avoids and issue where a new metric could be added
to a dictionary while iterating over it, raising a 
RuntimeError.
closes #717
=> iterate over a copy of metrics to avoid threading issues

tests/requirements/requirements-base.txt
The recently released 0.11.0 requires pytest 5+, which doesn't support
Python 2.7
=> pin pytest-asyncio to 0.10.0

elasticapm/instrumentation/packages/pymongo.py, tests/instrumentation/pymongo_tests.py
instance.address is not set on those versions
=> work around issue on pymongo < 3.0

elasticapm/instrumentation/packages/tornado.py, tests/contrib/asyncio/tornado/tornado_tests.py
If `tornado` is in use but not as the "main" instrumented framework (such as with `flower`), the instrumentation throws an error because the elasticapm_client cannot be found.
This PR checks for that case and skips all of the instrumentation work.
Closes #811
=> Check for missing elasticapm_client in tornado instrumentation

elasticapm/contrib/django/client.py, elasticapm/contrib/flask/utils.py, elasticapm/contrib/starlette/utils.py, tests/contrib/django/django_tests.py
So far, we still looked at the request body, even if capture_body
was disabled. This was so we only set the `[REDACTED]` flag if
there actually was a body. Unfortunately, this interferes with
streaming requests.
I haven't found a way to properly test this. Any suggestions?
closes #816
=> don't touch body if capture_body is False

Jenkinsfile
Fixes the code coverage when a build failure.
```
19:11:49  [Pipeline] { (Declarative: Post Actions)
19:11:49  [Pipeline] deleteDir
19:11:49  [Pipeline] unstash
19:11:49  [Pipeline] unstash
19:11:49  Error when executing cleanup post condition:
19:11:49  hudson.AbortException: No such saved stash ‘packages’
19:11:49  	at org.jenkinsci.plugins.workflow.flow.StashManager.unstash(StashManager.java:159)
```
Otherwise the build notifications will not happen and therefore the GH PR comment will create a new comment rather than reusing the existing one.
closes #ISSUE
=> ci: post build within the test stage context

setup.py, tests/contrib/asyncio/starlette_tests.py, tests/requirements/reqs-starlette-0.13.txt
Stops installing dependencies that aren't required, when installing with the `starlette` flag.
I'm not sure if there's a reason, but I haven't been able to find one. I noticed that when installing using `apm-agent[starlette]`, both `Flask` and `requests` were also installed, which seemed unnecessary.
I can't see any place where requests is actually used, but there was a reference to flask in a test. That test does seem flawed though, since it seems to mock `TraceParent` from the flask package, instead of the starlette package.
Not much, but it saves two dependencies that shouldn't be needed when installing.
Note that I haven't been able to run tests locally (it seems like there's a big setup required), so sorry in advance if the packages were actually required somehow, and the CI freaks …
=> Do not install flask and requets when installing starlette

tests/instrumentation/asyncio/elasticsearch_async_client_tests.py, tests/instrumentation/elasticsearch_tests.py
More small transaction name changes due to API flexibility.
=> Fix elasticsearch-py tests for new upstream release

docs/flask.asciidoc, docs/troubleshooting.asciidoc, elasticapm/handlers/logging.py, tests/handlers/logging/logging_tests.py
This is a result of some questions on a support ticket.`LoggingHandler` should not be possible to instantiate without a `Client` object (unless `client_cls` is passed in). Otherwise we can end up with a `LoggingHandler` with a default-config `Client` object that it self-creates and that can cause a lot of hard to debug issues.
The user was also trying to use `ElasticAPM(app, logging=logging.DEBUG)` to increase the log level of the agent, when it's actually meant to ship logs to Elasticsearch. I added some clarification to the docs.
=> Fix LoggingHandler Client requirements, plus some docs

elasticapm/utils/compat.py
The `ImportError` will be raised if `uwsgi` package is not installed. But if installed yet not _in use_, like during a Django's `./manage.py runserver` or on tests, the raised error will be AttributeError over uwsgi.masterpid .
=> Support uwsgi installed but not being used

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/asyncio/elasticsearch.py, elasticapm/instrumentation/packages/elasticsearch.py, elasticapm/instrumentation/register.py, tests/instrumentation/asyncio/async_elasticsearch_client_tests.py, tests/requirements/reqs-elasticsearch-7.txt
Adds support for `elasticsearch.AsyncElasticsearch` which is going to be released with elasticsearch-py v7.8.0. I ran the test suite against `elasticsearch==7.8.0a1` which passed but left the requirements file to only use released versions.
Let me know if any of the changes to the existing ES instrumentation shouldn't be modified. I made these changes under the impression that these were private APIs :)
=> Add support for AsyncElasticsearch

CHANGELOG.asciidoc, elasticapm/contrib/django/utils.py
See https://discuss.elastic.co/t/python-agent-raise-valueerror/233263
This is not an ideal solution, but I've investigated every code path into this function and I cannot see how the user could see that error. For now we'll just avoid throwing the error and see if any other users see it.
=> Add some error handling around frame processing

elasticapm/contrib/django/management/commands/elasticapm.py, elasticapm/transport/base.py, elasticapm/transport/exceptions.py, elasticapm/transport/http.py, tests/contrib/django/django_tests.py, tests/transports/test_base.py, tests/transports/test_urllib3.py
Due to a refactor in the past, the Django test command did
not print an error anymore when sending a message to the
APM Server failed. Added a fix and test.
=> print error message when submit fails in Django test command

Makefile, elasticapm/instrumentation/register.py, tests/requirements/reqs-base.txt
The old elasticsearch-async tests were skipped on py3.5 due to [this requirements line](https://github.com/elastic/apm-agent-python/blob/e9dcba55185d90601b4a048483c054ea36d108cd/tests/requirements/reqs-elasticsearch-7.txt#L2). However, as of 7.8.0, the main elasticsearch-py library contains async support, so we need an explicit `skipif` for the new tests on py3.5.
=> Skip new elasticsearch_async tests for <py3.6

CHANGELOG.asciidoc, docs/configuration.asciidoc
=> Add changelog and a couple of docs fixes for #860

Jenkinsfile
Global timeout affects the whole pipeline even if a particular stage got another timeout.
This will help to wait for 12 hours when a release happens, otherwise 1 hour as usual, for such I moved all the stages that are not release ones under the Initializing one
closes #ISSUE
=> [ci] support timeout per stages

tests/requirements/reqs-aiohttp-3.0.txt
asyncio.Task.current_task was removed in Python 3.9, and
a check for that was introduced in aiohttp 3.0.8
=> aiohttp 3.0.8+ is required for Python 3.9+ compatibility

CHANGELOG.asciidoc, docs/configuration.asciidoc, elasticapm/base.py
Ref https://github.com/elastic/apm/issues/289
=> Update CLOUD_PROVIDER for new valid options

tests/client/client_tests.py
See https://apm-ci.elastic.co/job/apm-agent-python/job/apm-agent-python-mbp/job/master/290/testReport/junit/tests.client/client_tests/Initializing___Test___windows_3_6_none___test_send_remote_failover_sync_validating_httpserver0_sending_elasticapm_client0_/ 
Compared with other flakiness issues with pytest-localserver, the stack trace is different,
but I suspect this is because they stack trace is masked.
=> mark another test as flaky

CHANGELOG.asciidoc, elasticapm/utils/cloud.py
It turns out for docker containers on AWS elastic beanstalk, the PUT for the
token fails, and fails slowly. This is not the case for the ec2 host on which
the docker container is running. This was causing issues, compounded by the
fact that I didn't have `retries=False` on that call.
I also made the timeouts shorter -- all of these calls are local, so they're very fast.
Fixes #880
=> Better error handling for AWS token fetching

docs/logging.asciidoc
As of https://github.com/elastic/ecs-logging-python/issues/13, `ecs-logging` automatically includes the required fields for distributed tracing. Users should go there first.
=> Add ecs-logging to log correlation docs

CONTRIBUTING.md, README.rst, docs/run-tests-locally.asciidoc
As noted in #844, we needed a bit more clarity as to how to run the test suite locally outside of docker. I added documentation around that case, and also added a direct pointer from our README.
I also added some more instructions about testing to CONTRIBUTING.md and linked to that document from the README as well. Hopefully that will remove some friction to new contributors.
=> Add more options for running tests locally

elasticapm/version.py, setup.cfg, setup.py
This should make this information easier to discover for tools like Snyk.
Also, it's the new and fresh way to do things :)
=> move most of the setup.py metadata and requirements to setup.cfg

Jenkinsfile
Use `<major>.<minor>.<patch>` versions when bumping the agent version in the opbeans-python
=> [CI] skip pre/post tags when opbeans-python version bump

docs/api.asciidoc, elasticapm/__init__.py, elasticapm/conf/constants.py, elasticapm/contrib/aiohttp/middleware.py, elasticapm/contrib/celery/__init__.py, elasticapm/contrib/django/middleware/__init__.py, elasticapm/contrib/flask/__init__.py, elasticapm/contrib/starlette/__init__.py, elasticapm/instrumentation/packages/asyncio/aiohttp_client.py, elasticapm/instrumentation/packages/requests.py, elasticapm/instrumentation/packages/tornado.py, elasticapm/instrumentation/packages/urllib.py, elasticapm/instrumentation/packages/urllib3.py, elasticapm/traces.py, tests/contrib/asyncio/aiohttp_web_tests.py, tests/contrib/asyncio/starlette_tests.py, tests/contrib/asyncio/tornado/tornado_tests.py, tests/contrib/celery/django_tests.py, tests/contrib/celery/flask_tests.py, tests/contrib/django/django_tests.py, tests/contrib/django/testapp/middleware.py, tests/contrib/django/testapp/urls.py, tests/contrib/django/testapp/views.py, tests/contrib/flask/flask_tests.py, tests/instrumentation/asyncio/aiohttp_client_tests.py, tests/instrumentation/base_tests.py, tests/instrumentation/requests_tests.py, tests/instrumentation/urllib3_tests.py, tests/instrumentation/urllib_tests.py
This implements https://github.com/elastic/apm/pull/299.
Additionally, the "status_code" attribute has been added to HTTP spans.
=> implement "outcome" property for transactions and spans

docs/starlette.asciidoc
* Rename variable `elasticapm` to `apm` so that the code works for the examples `apm.client.capture_exception()` and `apm.client.capture_message('hello, world!')` in the [usage section](https://www.elastic.co/guide/en/apm/agent/python/master/starlette-support.html#starlette-usage)
* Also, avoids conflicts when `import elasticapm` is also used
=> Rename variable elasticapm to apm

Jenkinsfile
It adds a couple of catchError steps to avoid failure when the stash does not exist
closes https://github.com/elastic/apm-agent-python/issues/913
=> fix: ignore unstash coverage errors

Jenkinsfile
The wrapt c-extension doesn't build with pypy, and our setup.py skips building the extension
when it detects pypy. However, we still mistakenly built pypy-specific binary wheels.
cibuildwheel introduced a check for this in 1.6, alerting us to the problem.
=> disable building binary wheels for pypy

docs/supported-technologies.asciidoc
While compiling a list of supported technologies, I realized that some were missing from our [supported technologies doc](https://www.elastic.co/guide/en/apm/agent/python/current/supported-technologies.html).
This PR adds those missing technologies.
=> Add missing technologies to support matrix

.ci/.jenkins_exclude.yml, .ci/.jenkins_framework_full.yml, elasticapm/instrumentation/packages/asyncio/httpcore.py, elasticapm/instrumentation/packages/httpcore.py, tests/requirements/reqs-httpx-0.14.txt
This fixes the httpx tests that are failing since the 0.11.0 release of httpcore (and the 0.15.0 release of httpx).
Just a small API change for retrieving the status code, and the async version of requests in httpcore is now `arequest` instead of `request` for namespacing.
=> Update httpcore instrumentation for 0.11.0 compatibility

CHANGELOG.asciidoc, elasticapm/conf/__init__.py, tests/config/tests.py, tests/contrib/django/django_tests.py
If a key wasn't provided, we didn't check if it was required or not.
This led to a problem that if no `service_name` was configured,
we'd send invalid data to APM Server.
fixes #921
=> fix handling of required keys in configuration

CONTRIBUTING.md
Ref #925 
For python <3.5 we need some exclude flags passed into `py.test`, which is handled automatically by `make test`.
=> Update contributing docs to recommend `make test` over `py.test`

.pre-commit-config.yaml, Makefile, elasticapm/contrib/django/apps.py, elasticapm/contrib/opentracing/span.py, elasticapm/instrumentation/packages/tornado.py, elasticapm/utils/compat.py, setup.cfg, tests/client/exception_tests.py, tests/contrib/django/django_tests.py, tests/contrib/django/fixtures.py, tests/contrib/django/testapp/celery.py, tests/instrumentation/asyncio_tests/elasticsearch_async_client_tests.py, tests/instrumentation/django_tests/template_tests.py, tests/instrumentation/urllib_tests.py
While I was fixing `isort` behavior in my IDE for the umpteenth time, I noticed that we're running a fairly old version of isort. After reading the [guide to upgrading to 5.x](https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/) I realized we were missing out on some real goodness in terms of `isort`'s ability to automatically categorize imports and the like.
You'll note that the changes in actual behavior were pretty minimal, despite removing most of our isort config.
The biggest change to moving to a largely default config was that django is now not its own section. You'll see from the diff that that's actually not a very big deal, but I'm open to reintroducing that as a section if we want to.
@beniwohli Thoughts?
=> Upgrade to isort v5.5.4

elasticapm/instrumentation/packages/asyncio/asyncpg.py, tests/instrumentation/asyncio_tests/asyncpg_tests.py
Issue #889 added instrumentation for asyncpg, though only `execute` and
`executemany` were instrumented. This extends the instrumentation to
include `fetch`, `fetchval` and `fetchrow` methods.
=> Extend asyncpg instrumentation in Elastic APM

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/elasticsearch.py, tests/instrumentation/asyncio_tests/async_elasticsearch_client_tests.py, tests/instrumentation/asyncio_tests/elasticsearch_async_client_tests.py, tests/instrumentation/elasticsearch_tests.py
See https://discuss.elastic.co/t/apm-not-showing-aggregation/250762
for context.
Basically, by only including the query, we risk missing very useful
pieces of the query for diagnosing issues -- `aggs` is the big problem
here but I don't see why the user wouldn't want the entire query every
time.
=> Include whole body for elasticsearch-py queries

scripts/run-tests.bat, tests/utils/tests.py
Using `call` swallows the exit code of the test runner, making
Jenkins mark failed test runs as unstable instead of failed.
=> fix test result output on Windows

docs/api.asciidoc, elasticapm/__init__.py, elasticapm/traces.py, tests/instrumentation/transactions_store_tests.py
Add a new public API to easily return the trace parent header of the current transaction, currently it's necessary to dig into the project and understand how it works.
Code necessary to get the current trace parent header without the new function.
```
from elasticapm.traces import execution_context
transaction = execution_context.get_transaction().
trace_parent_header = transaction .trace_parent.to_string() if transaction and transaction.trace_parent else None
```
https://github.com/elastic/apm-agent-python/issues/954
=> Add public API to retrieve trace parent header.

docs/api.asciidoc
This PR fixes a doc build error introduced in #956. The ID `api-traceparent-get-header` was already in use.
=> docs: Fix Elastic doc build

CHANGELOG.asciidoc, docs/configuration.asciidoc, elasticapm/base.py, elasticapm/conf/__init__.py, elasticapm/contrib/asyncio/traces.py, elasticapm/contrib/django/middleware/__init__.py, elasticapm/traces.py, tests/config/tests.py, tests/fixtures.py, tests/handlers/logging/logging_tests.py, tests/instrumentation/base_tests.py
Adds support for configurable `log_level`.
[Spec](https://github.com/elastic/apm/blob/master/specs/agents/logging.md)
Closes #941
=> Add log_level config

elasticapm/processors.py, tests/processors/tests.py
if any of the sanitized values is shorter than the replacement string
(`********`), we could potentially end up with the sanitized string that
is longer than the max length for a keyword field (1024). This
would make the event fail the JSONSchema validation.
=> ensure that query string max length is maintained after sanitization

.ci/.jenkins_windows.yml
we experience a lot of failed test runs on Windows/Python2.7 due to
a race condition happening in the coverage library.
We will drop support for Python 2.7 soon anyway, so it's not worth
investigating this further.
=> remove Python 2.7 testing on Windows

elasticapm/contrib/starlette/__init__.py, tests/contrib/asyncio/starlette_tests.py
Unfortunately, we need to do some matching here that Starlette does
too, but currently isn't exposed. If/when https://github.com/encode/starlette/pull/804
is merged, we can re-use the route from there.
closes #833
=> Starlette: use route name as transaction name if available

docs/metrics.asciidoc, elasticapm/metrics/sets/cpu_linux.py, tests/metrics/cpu_linux_tests.py
this was included by mistake.
Also, add docs for the two remaining cgroup fields
=> remove system.process.cgroup.memory.stats.inactive_file.bytes

tests/contrib/asyncio/starlette_tests.py
The behavior that we test was only introduced in 0.14
=> skip trailing slash tests in starlette < 0.13

elasticapm/__init__.py
pkg_resources is very slow as can be seen in this simple test:
```
> time python -c "print( __import__('pkg_resources').get_distribution('elastic-apm').version)"
4.2.2
0.33 real         0.24 user         0.08 sys
> time python -c "from importlib.metadata import version; print(version('elastic-apm'))"
4.2.2
0.08 real         0.05 user         0.02 sys
> time python -c ""                   Wed Dec  2 09:36:26 2020
0.03 real         0.02 user         0.01 sys
```
=> Avoid the slow pkg_resources package on modern python versions

elasticapm/metrics/sets/cpu_linux.py, tests/metrics/cpu_linux_tests.py
Apparently, it's possible for an environment to have the
memory.limit_in_bytes file, but not the memory.usage_in_bytes.
To avoid raising FileDoesNotExist errors, we now check if the
files are readable when the metric set is initialized.
closes #985
=> fix for #985

.ci/.jenkins_windows.yml, scripts/install-tools.bat, scripts/run-tests.bat
psutil doesn't provide binary wheels anymore, and we intend to
remove Python 3.5 support soon anyway.
As an added bonus, let's activate Python 3.9 testing on Windows,
since the latest psutil release has binary wheels for 3.9
=> remove Python 3.5 on Windows testing

elasticapm/instrumentation/packages/psycopg2.py, tests/instrumentation/psycopg2_tests.py
The query might be supplied as already encoded byte string (e.g. when using `psycopg2.extras.execute_values`). In this case, truncation of the query fails unless we decode the query again using the connection encoding.
closes #991
=> properly support already-encoded SQL strings with psycopg2

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/asyncio/elasticsearch.py, elasticapm/instrumentation/packages/elasticsearch.py, tests/instrumentation/asyncio_tests/async_elasticsearch_client_tests.py, tests/instrumentation/elasticsearch_tests.py
Uses the Elasticsearch serializer for better compatibility
Closes #997
=> Fix for json-incompatible elasticsearch bodies

docs/supported-technologies.asciidoc
This PR makes a small change in python-memacached library name.
I think that the package name should be used instead of the imported library name for clarity (or at least referenced alongside).
Until I looked at the code, I thought that python-memcached was not supported based on the documentation, so hopefully this may save a little time for someone.
=> Fix python-memcached package name

.pre-commit-config.yaml, CHANGELOG.asciidoc, elasticapm/contrib/starlette/__init__.py, tests/contrib/asyncio/starlette_tests.py
Noticed that we were gating instrumentation for starlette only on `config.instrument` -- we need to also gate on `config.enabled` to make sure we don't instrument when we shouldn't.
Ref #993
=> Fix starlette to not instrument when enabled=False

tests/contrib/asyncio/aiohttp_web_tests.py, tests/contrib/asyncio/tornado/tornado_tests.py, tests/contrib/django/fixtures.py, tests/contrib/flask/fixtures.py, tests/contrib/opentracing/tests.py
Found an issue while writing a test for https://github.com/elastic/apm-agent-python/pull/1000 -- the test fixture wasn't calling `uninstrument()`. A brief search revealed that this is the case across all of our framework fixtures. This PR resolves this issue for the remaining framework fixtures.
=> Fix test fixtures to uninstrument

elasticapm/handlers/logging.py, elasticapm/handlers/structlog.py, tests/handlers/logging/logging_tests.py
During the latest agents weekly meeting, it was pointed out that we should be including service.name alongside the other fields we populate for ecs-logging. This PR adds that field.
Once we release 5.10.1 we will need to also update ecs-logging-python and its tests.
=> Add service.name to logging integrations

elasticapm/instrumentation/packages/graphql.py, tests/instrumentation/graphql_tests.py
Do not create spans for scalar fields with a required flag, because it causing span spamming.
Before this commit it's worked only for optional fields.
=> Fix GraphQL instrumentation: span spamming

.ci/.jenkins_exclude.yml, .ci/.jenkins_python.yml, CHANGELOG.asciidoc, Jenkinsfile, elasticapm/__init__.py, setup.cfg
Removes support for python2, pypy2, and python 3.5
Fixes #928 
Fixes #929
=> Remove support for python2, pypy2, and python 3.5

CHANGELOG.asciidoc, docs/upgrading.asciidoc, elasticapm/__init__.py, elasticapm/traces.py, tests/client/client_tests.py, tests/client/exception_tests.py, tests/instrumentation/transactions_store_tests.py
The docs changes were large enough I wanted to make sure there were no docs build errors before I cut the 6.0.0 release.
=> Remove tags (deprecated) + Update docs for 6.x

tests/requirements/reqs-base.txt, tests/transports/test_urllib3.py
pytest-bdd isn't updated all the way, as it introduced a few
backwards incompatibilities that need to be fixed first
A test of urllib3 had to be modified slightly, as some
requirement update seems to truncate the error message we
are looking for. It's not quite clear where this happens.
=> with Python 2 support gone, we can update a bunch of requirements

CHANGELOG.asciidoc, elasticapm/contrib/starlette/__init__.py, elasticapm/contrib/starlette/utils.py, tests/contrib/asyncio/starlette_tests.py
Because Starlette does not propagate the cached `request._body` properly, we've always had to use a [hack](https://github.com/encode/starlette/issues/495#issuecomment-513138055) in order to make sure we don't hang requests by streaming the body before the request does.
This PR ensures that for any `capture_body` setting that's not `off`, we perform this hack in the pre-request stage so that everyone will have easy access to the body down the line.
Before this fix, if `capture_body` was set to `error`, and an error was thrown after the body was already streamed, we would hang while trying to capture the body. I consider this a [bug in Starlette](https://github.com/encode/starlette/issues/495) but this should let us work around it.
Fixes #1032
=> Fix for hang on capture_body: error in starlette

docs/configuration.asciidoc, elasticapm/base.py, elasticapm/conf/__init__.py, tests/contrib/django/django_tests.py
Adds a default for all required configuration values. This allows the agent to be used with zero configuration alongside something like the Fleet Agent. We don't do any fancy detection around the `SERVICE_NAME`, it just defaults to `python_service` (and logs a warning if it's not overridden by the user).
"Zero-configuration" is actually pretty worthless by itself, but the hope is that along with #1019 we should be able to allow the user to onboard with no code changes and just an invocation change.
Fixes #1008
=> Add defaults for all required config values

CHANGELOG.asciidoc, elasticapm/contrib/starlette/utils.py, tests/contrib/asyncio/starlette_tests.py
I realized while debugging #1032 that we were erroneously sending the request body as a parsed-from-json object, rather than a string as the [spec](https://github.com/elastic/apm-server/blob/af4f9fe07ac714771526ef562e6618c6189e38fd/docs/spec/v2/error.json#L46-L52) requires. This PR fixes that.
Fixes #1032 (again)
=> Send request body as a string in Starlette

CHANGELOG.asciidoc, elasticapm/traces.py
=> Only process frames if they exist

CHANGELOG.asciidoc, elasticapm/contrib/starlette/__init__.py, tests/contrib/asyncio/starlette_tests.py
Fix transaction names for starlette [Mount](https://www.starlette.io/routing/#submounting-routes) routes. 
Recursively build route names for mounted sub-applications.
closes #1036 
*Note: Opened it as a draft pull request because I couldn't write tests yet, but I still wanted to give you an idea of a potential fix.*
=> Fix transaction names for starlette Mount routes

elasticapm/contrib/starlette/utils.py
#1038 hack the request to make everyone access, but there is still a chance of hanging. 
apm-agent-python use the [following code](https://github.com/elastic/apm-agent-python/commit/6cffb0ecbf93f442b4f2bcbf3fb1a95dc6049451#diff-f9e770f7326cda6eb54ca0dd8842e87343851916da33047083fde4810ee438b0R110-R111) to act a function to return starlette Message
```python
async def receive() -> Message:
return {"type": "http.request", "body": body}
```
And it will be calling and hanging by [starlette Response process](https://github.com/encode/starlette/blob/master/starlette/responses.py#L223-L230)
`receive` what we declared will be passed as parameter `receive` to `__call__` and will hang in `run_until_first_complete`
Cause according [PEP492](https://www.python.org/dev/peps/pep-0492/#await-expression)
> …
=> Fix starlette/fastapi hang on capture_body 

CHANGELOG.asciidoc, docs/configuration.asciidoc, elasticapm/conf/__init__.py, tests/fixtures.py, tests/handlers/logging/logging_tests.py, tests/requirements/reqs-base.txt
Adds a new config value, called `auto_ecs_logging`, which defaults to False. If the user sets this value to True (and has `ecs_logging` installed), we will do two things:
1. Call `setFormatter(ecs_logging.StdlibFormatter())` on each of the handlers on the root logger
2. Set the default processor for `structlog` (if installed) to `ecs_logging.StructlogFormatter()`.
I also documented the new setting and added a test.
Closes #1006
=> Add `auto_ecs_logging` config

elasticapm/contrib/django/handlers.py
We had a couple of transient errors around some of the logging tests in Django after the introduction of the global client in #1043. This should fix those issues.
=> Simplify client fetching in django.handlers.LoggingHandler

CHANGELOG.asciidoc, docs/configuration.asciidoc, elasticapm/conf/__init__.py, tests/handlers/logging/logging_tests.py
This matches the Java implementation which is more flexible (due
to using an enum instead of a bool) and will match the upcoming
ecs log formatting [spec](https://github.com/elastic/apm/pull/423)
Ref #1058 and #1006
=> Refactor auto_ecs_logging to log_ecs_formatting

docs/configuration.asciidoc
Documentation was omitted when merging #923 
closes #976
=> added docs for `transaction_ignore_urls`

elasticapm/instrumentation/packages/botocore.py, tests/instrumentation/botocore_tests.py
The service name and resource were nested wrongly, as reported in #1088 and #1089
closes #1088 
closes #1089
=> fix wrong destination nesting reported in #1088 and #1089

elasticapm/contrib/tornado/utils.py, tests/contrib/asyncio/tornado/tornado_tests.py, tests/fixtures.py
So far, only when using sending_elasticapm_client, events were validated.
This made us miss things like #1088 and #1089. With this change,
every single event is validated against the apm-server JSONSchema.
=> Validate every event created by the elasticapm_client test client

tests/upstream/json-specs/transaction.json
APM agent json schema automatic sync
*Changeset*
=> synchronize schema spec

elasticapm/contrib/django/middleware/__init__.py, tests/contrib/django/django_tests.py, tests/contrib/django/testapp/nameless_route_urls.py, tests/contrib/django/testapp/urls.py
=> fall back on url_name and func name if no route name is provided with Django

elasticapm/contrib/flask/__init__.py
Fix the issue #1098 by allowing the "build the application on the fly" feature for flask agent. This also fix backward compatibility with old versions.
closes #1098
=> fix flask undefined client

.ci/.jenkins_exclude.yml
=> temporarily exclude pypy-3 from testing as it fails, possibly due to ecs-logging

.ci/.jenkins_exclude.yml
pypy-3 gained support for the `async` keyword, making code fail that uses
`async` as an identifier. Such as old versions of pyscopg2cffi.
=> exclude pypy-3/psycopg-2.7

elasticapm/instrumentation/packages/asyncio/asyncpg.py
Adds database(postgres) as a dependency in python elastic apm for asyncpg instrumentation
I have taken the code from psycopg2 instrumentation which is able to show database as a dependency. Ran these changes locally and I can now see postgres under dependencies.
Related issues
closes #1111
=> add database as a dependency in asyncpg instrumentation

elasticapm/contrib/django/client.py
=> Add drf Request support

elasticapm/instrumentation/packages/asyncio/httpcore.py, elasticapm/instrumentation/packages/httpcore.py, tests/instrumentation/asyncio_tests/httpx_tests.py, tests/instrumentation/httpx_tests.py
The newly released httpx 0.18.0 and its dependency httpcore 0.13 changed some internals that affect us.
=> Fix httpx 0.18.0

setup.cfg, tests/instrumentation/pyodbc_tests.py
=> fix warnings raised for pyodbc

tests/bdd/api_key_tests.py, tests/requirements/reqs-base.txt
Most importantly, pytest 6.2.4 restores compatibility with Python 3.10 Beta
closes #ISSUE
=> update a bunch of requirements

elasticapm/utils/cloud.py
=> make sure to close sockets that we open to detect cloud environment

elasticapm/instrumentation/packages/asyncio/aioredis.py, elasticapm/instrumentation/packages/redis.py, tests/instrumentation/asyncio_tests/aioredis_tests.py, tests/instrumentation/redis_tests.py
=> Add Redis pub/sub instrumentation

.ci/.jenkins_framework_full.yml, tests/instrumentation/redis_tests.py, tests/requirements/reqs-redis-2.txt, tests/requirements/reqs-redis-3.0.txt, tests/requirements/reqs-redis-3.txt, tests/requirements/reqs-redis-newest.txt
the pubsub test uses a context manager API that isn't available on redis 2.
Also, don't test specific redis 2 versions, only the most recent 2.x
=> skip pubsub test on redis 2

.ci/.jenkins_exclude.yml, .ci/.jenkins_framework_full.yml, elasticapm/instrumentation/packages/asyncio/httpcore.py
this breaks distributed tracing, and it would be too much
work getting it to work on legacy libraries.
=> stop testing with httpx-0.12, as it doesn't use httpcore

tests/instrumentation/asyncio_tests/aioredis_tests.py
The reason for the flakines is as of yet unknown. It looks like the `execute_pubsub` method
sometimes isn't instrumented, which might point towards an import-time instrumentation-race.
A new version of aioredis will be released soon with completely rewritten internals.
The hope is that this issue will go away at that point.
Using `pytest.mark.flaky` isn't an option, as `flaky` doesn't support async tests.
=> skip flaky test in aioredis

elasticapm/base.py, elasticapm/metrics/base_metrics.py, elasticapm/transport/base.py, elasticapm/utils/threading.py, tests/metrics/base_tests.py
To ensure that the flushed metrics are actually sent, we need
to make sure that the transport thread is shut down last.
See also https://github.com/elastic/apm/pull/444
=> Ensure that metrics are flushed before shutting down

docs/sanitizing-data.asciidoc, elasticapm/transport/base.py, tests/processors/tests.py
Without this safeguard, exceptions in processors would bubble all the way
up, killing the transport thread. This would then result in the agent
stopping to report any data.
=> added a safeguard for processors that raise exceptions

elasticapm/utils/threading.py, tests/utils/threading_tests.py
Instead of letting the thread die, we log the exception with
a stack trace to ease debugging.
Specifically, we have a hard to debug exception in the configuration updater,
and need a stack trace to debug the issue. But this should be helpful in other
cases, too.
=> catch and log exceptions in the interval timer function

elasticapm/conf/__init__.py, tests/config/tests.py
This ensures that the attribute is set on VersionedConfig itself,
not on the proxied Config object. The later works, but only until
the configuration is updated and the Config object is switched out
with a new one that doesn't have the attribute.
fixes #1147
=> add start_stop_order to VersionedConfig.__slots__

conftest.py
this makes it a bit (not much) easier to tell in which matrix test exactly a test has run
in the Jenkins UI
=> include matrix info in pytest output

tests/utils/test_disttracing_header.py
this also tests that the w3c "traceparent" header has precedence over our legacy header
closes #1153
=> added test for TraceParent.from_headers

elasticapm/contrib/django/__init__.py, tests/contrib/django/django_tests.py
The attribute was deprecated in Django 3.2, defining it causes a `RemovedInDjango41Warning`.
fixes #1130
=> suppress the default_app_config attribute in Django 3.2+

elasticapm/base.py
it turns out that setting the agent multiple times can
result in difficult-to-debug issues, especially when
initially using the DjangoClient, and having it replaced
with a "bare" Client. See #1093, #1148
By bumping this log message to WARNING, it is a bit more
obvious what the problem could be.
=> bump log level for multiple set_client calls to WARNING

elasticapm/instrumentation/packages/botocore.py, tests/instrumentation/botocore_tests.py
also, closing some gaps in SQS testing
closes #1169
=> fix issue with adding disttracing to SQS messages when dropping spans

docs/configuration.asciidoc, elasticapm/conf/__init__.py, elasticapm/transport/http.py, tests/transports/test_urllib3.py
urllib3 will in this case fall back to the default mechanisms to find
a certificate store, see
https://www.python.org/dev/peps/pep-0476/#trust-database
closes #1162
=> make it possible to disable certifi

CHANGELOG.asciidoc, docs/supported-technologies.asciidoc
Our CI is testing against [lastest redis](https://github.com/elastic/apm-agent-python/blob/master/tests/requirements/reqs-redis-newest.txt) so we don't need this upper boundary.
Also updated the CHANGELOG from #1163
Fixes #1179
=> Fix redis supported technologies doc

tests/contrib/asyncio/starlette_tests.py
Turns out we did have a lint error in #1174 -- not sure how it slipped through the tests run on the PR.
This fixes those lint errors, even though they're not erroring upstream because pre-commit only runs on changes. (Maybe we need to revisit that?)
For any who are interested, [this](https://github.com/PyCQA/isort/issues/1337) is why the `# isort:skip` wasn't working. If we wanted to have the `import os` at the top we would have to use `# isort:split`.
Fixes #1181
=> Fix isort lint for starlette_tests.py

elasticapm/contrib/starlette/__init__.py
For scope types that we do not support, raising an exception seems to be the appropriate way to signal the lack of support to the server, see e.g. https://www.uvicorn.org/#the-asgi-interface
> It's good practice for applications to raise an exception on scope types that they do not handle.
Without this, the server could wait forever for us to handle a scope that we do not support.
closes #1184
=> raise an exception for non-http scopes in the Starlette middleware

CHANGELOG.asciidoc, elasticapm/contrib/starlette/__init__.py, tests/contrib/asyncio/starlette_tests.py
Raising an error as we do in #1185 is not the correct behavior for non-http scopes in our middleware. Just because we don't handle non-http scopes doesn't mean Starlette/FastAPI can't. Instead of raising an exception, we just need to skip all of our processing and await the app and immediately return.
I verified that this works as a fix for both #1184 and #1186.
Closes #1186
=> Fix Starlette/FastAPI middleware for non-http scopes

elasticapm/instrumentation/packages/elasticsearch.py, tests/instrumentation/elasticsearch_tests.py
If the elasticsearch span is dropped for some reason, the context object
is None, which, if unhandled, leads to an exception
closes #1188
=> ensure that the elasticsearch instrumentation handles DroppedSpans correctly

tests/requirements/reqs-starlette-0.14.txt
The requirement went forgotten in the 0.14 requirements file, it's there for the other versions.
=> add aiofiles to starlette-0.14 requirements file

docs/configuration.asciidoc
The [spec](https://github.com/elastic/apm/blob/master/specs/agents/log-onboarding.md) defines this option as experimental, which I failed to do when I originally introduced it.
=> Mark `log_ecs_formatting` as experimental

elasticapm/base.py, elasticapm/conf/constants.py, elasticapm/transport/http.py, elasticapm/transport/http_base.py, tests/contrib/django/fixtures.py, tests/fixtures.py, tests/transports/test_urllib3.py
this will allow putting new features behind version guards, e.g.
only sending histogram metrics to server versions that understand
it
=> fetch server version on transport thread start

elasticapm/transport/http.py
In cases where the response from APM Server is very large,
the log is spammed with extremely long log messages.
=> limit the transport exception message to 10000 characters

.ci/jobs/apm-agent-python-mbp.yml
Filters to only the currently supported branches.
Current view:
Proposed view:
This is per a discussion with @basepi in a private repo. I will link back to this issue from there.
=> Filter to supported Jenkins branches

CHANGELOG.asciidoc, elasticapm/utils/json_encoder.py, tests/utils/json_utils/tests.py
Fixes the default case for json serialization so we never throw an error and interrupt the host application.
Closes #1202
=> Never error in json serialization

.pre-commit-config.yaml, CHANGELOG.asciidoc, elasticapm/processors.py, tests/processors/tests.py
Sometimes, the `cookie` header is actually `Cookie`, so check for both if there's an error.
Closes #1297
=> Fix cookie sanitization if Cookie is capitalized

tests/requirements/reqs-base.txt
That specific version has a bug on Python 3.10
See https://github.com/python/typing/issues/865
closes #ISSUE
=> avoid typing_extensions 3.10.0.1

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/asyncio/aioredis.py, tests/instrumentation/asyncio_tests/aioredis_tests.py
=> only try to decode aioredis command if it is a bytes object

docs/supported-technologies.asciidoc
Support was added in https://github.com/elastic/apm-agent-python/pull/1064
=> Add Django 3.2 to supported technologies doc

tests/handlers/logging/logging_tests.py
this client will start to try making connections to the default
APM Server, fail to reach it, and spam the log with connection
errors.
We can avoid this by using a dummy transport
=> don't initialize a client with a real transport in logging test

elasticapm/instrumentation/packages/asyncio/asyncpg.py, tests/instrumentation/asyncio_tests/asyncpg_tests.py
Hey guys,
So I've noticed that the ElasticAPM Python Agent was not binding itself to the right methods to gather AsyncPG data. I've taken a look at how the NewRelic Agent did it and came up with this modification. So instead of using the Connection object, which is sometimes not used (i.e: sqlalchemy) Im binding at the protocol layer to ensure no spans are missed.
I have been running this on production for a while now and it's great :)
Enjoy
=> Fixed AsyncPG Integration who missed a lot of spans

CHANGELOG.asciidoc, elasticapm/contrib/aiohttp/__init__.py, elasticapm/contrib/aiohttp/middleware.py
`elasticapm.contrib.aiohttp.ElasticAPM` allows an optional client
instance as argument, though that client is not used in the tracing
middleware. Instead, it always uses the `base` modules client singleton.
This change passes the client object to the tracing middleware allowing
for a consistent use of a custom client object.
=> Pass custom client to aiohttp tracing middleware

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/asyncio/httpx.py, elasticapm/instrumentation/packages/httpx.py, tests/instrumentation/asyncio_tests/httpx_tests.py, tests/instrumentation/httpx_tests.py
The issue is that `some_dict.get("x", alt)` doesn't short-circuit,
so `alt` is always evaluated.
closes #1336
=> fix issue in httpx instrumentation when request is a kwarg

CHANGELOG.asciidoc, elasticapm/contrib/django/client.py, elasticapm/contrib/django/utils.py
=> re-implement HttpRequest.get_raw_uri that is removed in Django 4.0

elasticapm/transport/http.py, tests/transports/test_urllib3.py
If an HTTP response comes back from the "server" but isn't formed correctly, we can get the following error:
```
version = data["version"]
TypeError: 'int' object is not subscriptable
```
This came up when testing against the new (upcoming) lambda extension. Apparently it responded, but not with useful data. This PR fixes that error.
Ref #1194
=> Handle TypeError for missing server version

CHANGELOG.asciidoc, elasticapm/traces.py, tests/client/span_compression_tests.py
this ensures that compressed spans are not counted against
transaction_max_spans
alternative for #1376
=> decrement span_counter when span is compressed

CHANGELOG.asciidoc, elasticapm/base.py, elasticapm/transport/http_base.py, tests/client/client_tests.py
Updates the User-Agent header to match the spec in https://github.com/elastic/apm/pull/514
Remaining:
Closes #1355
=> Update User-Agent to match spec

CHANGELOG.asciidoc, elasticapm/contrib/serverless/aws.py, tests/contrib/serverless/aws_tests.py
Better error handling for the `Xxx` conversion, and remove case-insensitive `statusCode` handling, as anything besides `statusCode` is invalid and will throw a server error.
Edit: Also added the field changes from spec PR here: https://github.com/elastic/apm/pull/540
=> More AWS Lambda improvements and spec changes

CHANGELOG.asciidoc, elasticapm/base.py, elasticapm/instrumentation/packages/psycopg2.py, tests/fixtures.py, tests/instrumentation/psycopg2_tests.py
=> fix issue with multiple hosts/ports in psycopg2 connect span

.ci/.jenkins_framework_full.yml, tests/requirements/reqs-aiohttp-4.0.txt
it appears that aiohttp abandoned that release train and continues
development on 3.x
closes #1391
=> remove aiohttp 4.0 from tests, as the last alpha is from 2019

CHANGELOG.asciidoc, elasticapm/traces.py, tests/instrumentation/transactions_store_tests.py
I decided not to do any error handling around casting to `str()` as suggested in #1167 -- while theoretically it can throw errors, the user would have to be doing something exceptionally odd to make that happen and I don't think it's worth muddying the code. We cast to `str()` regularly without error handling.
Closes #1167
=> Cast transaction name to str

.ci/.jenkins_exclude.yml, .ci/.jenkins_python.yml, setup.cfg, tests/requirements/reqs-boto3-newest.txt
also, rename pytion-3.10-rc to python-3.10 and clean up some other
excludes
closes #ISSUE
=> sanic-20.12 requires an old uvloop version not supported in Python 3.10

.ci/linting.groovy, Jenkinsfile
It changes the message to trigger the linting from `jenkins run the linters please` to `/test linters` we will add the message to the comment in PR to do not have to remember it.
It also makes shorter the messages to launch the benchmarks and the full matrix tests `/test full` and `/test benchmark` now
NOTE: the message will not activate until we merge the PR
=> chore: change the linting message to looks like the rest

CHANGELOG.asciidoc, elasticapm/conf/__init__.py
see https://github.com/elastic/apm/blob/5e1bfbc95fa0358ef195cedba8cb1be281988227/specs/agents/handling-huge-traces/tracing-spans-compress.md#configuration-option-span_compression_exact_match_max_duration
=> fix default value for span_compression_exact_match_max_duration

elasticapm/contrib/sanic/utils.py
In the current `master`, the Sanic integration copies the entire `sanic.config.Config` object. This object includes some non-configuration values, which are not relevant to capturing in the environment context.
Furthermore, in Sanic v21.9.2, a change was introduced that added a reference to an object that could not be properly copied here: https://github.com/ahopkins/apm-agent-python/blob/060cec6efa22eecfaf773c2df935b6642f841bab/elasticapm/base.py#L456
This resulted in a failure for the response object to populate through the context and ultimately resulting in the error as seen in #1413.
This is a somewhat shortlived issue since the next version of Sanic will remove that. However, it underscores a flaw in this integration in that the only values that should be copied over from the …
=> Filter Sanic config object to only include configration values in context

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/asyncio/asyncpg.py, tests/instrumentation/asyncio_tests/asyncpg_tests.py
APM server allows events with a max size of 10000 characters. Shorten
queries traced in `asyncpg` to max allowed.
See: #842
Did not manage to run the tests for this locally. Will leave it to CI to tell me.
=> Shorten long SQL query to prevent oversized event

elasticapm/instrumentation/packages/pymongo.py, tests/instrumentation/pymongo_tests.py
pymongo 4.0 removed several methods that we instrument, so we should
not run tests for these on the 4.0+ versions. We already instrument
and test most replacements, except for `count_documents` and
`estimated_document_count`. Instrumentation and tests for these
have been added.
=> fix pymongo 4.0 test failures

tests/upstream/json-specs/span_types.json
*Changeset*
* https://github.com/elastic/apm/commit/35639b2 span type/subtype: alignment step 1 (https://github.com/elastic/apm/pull/513)
=> test: synchronizing json spec

CHANGELOG.asciidoc, elasticapm/base.py, elasticapm/contrib/django/middleware/__init__.py, tests/contrib/django/django_tests.py, tests/contrib/django/testapp/urls.py
also, move determination of transaction name in Django to earliest
possible moment.
closes #1409
=> add transaction name to error objects

.ci/.jenkins_python.yml, .ci/.jenkins_python_full.yml, .ci/nightly.groovy, .ci/packer_cache.sh, Jenkinsfile
the CI runs on PRs are getting prohibitively long. To work around
this, we can use only a limited set of Python versions for PR runs
and do a full, nightly run (the same approach we already use for
framework versions).
=> use a limited amount of Python versions for PR runs

.ci/.jenkins_framework.yml, .ci/.jenkins_framework_full.yml, tests/instrumentation/jinja2_tests/jinja2_tests.py, tests/requirements/reqs-base.txt, tests/requirements/reqs-django-1.11.txt, tests/requirements/reqs-django-2.0.txt, tests/requirements/reqs-django-2.1.txt, tests/requirements/reqs-django-2.2.txt, tests/requirements/reqs-django-3.0.txt, tests/requirements/reqs-django-3.1.txt, tests/requirements/reqs-django-3.2.txt, tests/requirements/reqs-django-4.0.txt, tests/requirements/reqs-django-master.txt, tests/requirements/reqs-flask-0.10.txt, tests/requirements/reqs-flask-0.11.txt, tests/requirements/reqs-flask-0.12.txt, tests/requirements/reqs-flask-1.0.txt, tests/requirements/reqs-flask-1.1.txt, tests/requirements/reqs-flask-2.0.txt, tests/requirements/reqs-jinja2-2.txt, tests/requirements/reqs-jinja2-3.txt, tests/scripts/envs/jinja2.sh
Remove flask-specific requirements from `reqs-base.txt`, and pin `MarkupSafe` to a compatible version for `flask < 2.0`
=> pin markupsafe for Flask < 2.0

elasticapm/transport/http.py
This log was added at `info` level, which was breaking the Django test command. We probably shouldn't be logging this so high anyway, it's debug information.
Closes #1465
=> Move the APM server fetch log to `debug`

docs/configuration.asciidoc
A customer was trying to use `API_KEY` in flask config as a lower-case config value. This fixes that config value to be more consistent with our other entries.
=> Fix inconsistent case for `API_KEY` config in docs

CHANGELOG.asciidoc, docs/configuration.asciidoc, elasticapm/conf/__init__.py, elasticapm/traces.py, tests/client/dropped_spans_tests.py, tests/config/config_snapshotting_tests.py
`Span.duration` is measured in seconds, but was compared to the millisecond value in `exit_span_min_duration`. This meant that exit spans with durations less than 1 second were being dropped. 😱 
This fixes that issue, and also turns of `exit_span_min_duration` by default, which is coming in https://github.com/elastic/apm/pull/610
Closes #1482 
Closes #1476 
Ref #1418
=> Fix exit_span_min_duration to properly use ms

.ci/jobs/apm-agent-python-linting-mbp.yml, .ci/jobs/apm-agent-python-mbp.yml, .ci/jobs/apm-agent-python-nightly-mbp.yml
Remove the periodic trigger as we don't really need this based on the webhook push based events. 
This will reduce the number of builds which have been stalled for quite some time.
In addition, this will help us to update the job definition and pick up the `main` branch which it's not available at the moment.
=> jjbb: remove periodic trigger

tests/bdd/features/otel_bridge.feature
*Changeset*
* https://github.com/elastic/apm/commit/48565ba OTel bridge spec (https://github.com/elastic/apm/pull/516)
=> test: synchronizing gherkin spec

CHANGELOG.asciidoc, elasticapm/contrib/serverless/aws.py, elasticapm/transport/base.py, elasticapm/transport/http.py, elasticapm/transport/http_base.py, tests/contrib/serverless/aws_sns_test_data.json, tests/contrib/serverless/aws_sqs_test_data.json, tests/contrib/serverless/aws_tests.py, tests/transports/test_base.py
Brings the lambda integration in line with the latest changes to the [spec](https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-aws-lambda.md)
Closes #1486
Closes #1446 
Refs https://github.com/elastic/apm/pull/614
Closes #1480 
Closes #1424
=> Lambda improvements

setup.cfg, tests/requirements/reqs-flask-1.0.txt, tests/requirements/reqs-flask-1.1.txt
A newly released version of jinja2 is incompatible with older flask versions. We work around this by running those tests with an older version of jinja2.
closes #1502
=> work around issue with older flask versions and newest jinja2 release

.ci/.jenkins_python_full.yml
django.db.utils.NotSupportedError: deterministic=True requires building _sqlite3 with SQLite 3.8.3 or higher
=> pypy tests fail with an SQLite error message on pypy

docs/opentracing.asciidoc
Removing the opentracing docs broke the docs build, as old versions of 6.x refer to the latest 6.x release's docs.
I've added the page back, but it's not linked on the index anymore so it should be invisible for docs flow purposes, but fix the errors.
=> Add back opentracing docs

CHANGELOG.asciidoc, elasticapm/traces.py, tests/client/transaction_tests.py
the issue wasn't originally caught in testing because we hard code
the server_version to a certain value (currently 8.0.0), and this
bug was in a branch that only is hit with a server version lower
than 7.16
fixes #1509
=> fix issue in span serialization when using APM Server < 7.16

.ci/packer_cache.sh
Avoid failing the packer_cache process.
https://github.com/elastic/apm-agent-python/issues/1505 broke the script, but the packer_cache should work on best-effort, so if possible then cache the images, otherwise do not fail.
Then the packer cache image generation can move on with the next packer_cache project. Otherwise, we won't be using latest cache images
=> ci: packer_cache never fail

tests/contrib/sanic/fixtures.py, tests/contrib/sanic/sanic_tests.py
See https://github.com/sanic-org/sanic/issues/2423 for some context.
Our Sanic tests were failing due to not being able to get the route from one of the requests.
It took me awhile to track down the issue, but it turns out the router stopped accepting `<name:string>` and wants `<name:str>` instead. This was not listed as a breaking change in their release notes, so I recommended they add it.
Closes #1515
=> Fix sanic tests

tests/contrib/sanic/sanic_tests.py
Sanic 20.12.3 supports `string` type but not `str` type. Sanic 22.3.0 supports `str` but not `string`. 🤦‍♂️ 
Skip the test for the old version, which is less important than the newest version.
=> Fix sanic tests for 20.12.x

.ci/.jenkins_exclude.yml, .ci/.jenkins_framework.yml, .ci/.jenkins_framework_full.yml, CHANGELOG.asciidoc, docs/supported-technologies.asciidoc, elasticapm/instrumentation/packages/asyncio/aiobotocore.py, elasticapm/instrumentation/packages/botocore.py, elasticapm/instrumentation/register.py, setup.cfg, tests/instrumentation/asyncio_tests/aiobotocore_tests.py, tests/requirements/reqs-aiobotocore-newest.txt, tests/scripts/envs/aiobotocore.sh
This adds instrumentation for aiobotocore. It heavily uses the existing instrumentation from boto3.
I got the tests to run locally for this, but noticed that the instrumentation of `aiohttp.client` already sends spans for `aiobotocore`. Though they are not labelled as AWS specific as the `boto3` instrumenter does.
As is, this implementation currently results in 2 spans for each request. I am looking for some advice on what is the better approach here. Try to remove the wrapper on the `ClientSession` used by `aiobotocore` or change the spans created by `ClientSession`?
Nothing opened (yet)
=> Add instrumentation for aiobotocore

Jenkinsfile
Use the new step for the code coverage
As soon as https://github.com/elastic/apm-pipeline-library/pull/1673 is merged and released then the code coverage report on a PR basis will be available
The below tests are the ones I used for supporting the GitHub comments with the Code Coverage delta between the PR and the target branch
If it cannot be compared with the target branch:
If it can be compared with the target branch:
=> ci: use coverageReport for code coverage

elasticapm/traces.py, tests/instrumentation/transactions_store_tests.py, tests/utils/__init__.py
This change conditionally logs a warning, based on the state of the APM integration (`ELASTIC_APM_ENABLED`), if no transaction is present and adding labels. It still warns developers when data is discarded and at the same time doesn't spam the log with unnecessary log lines in case the integration is disabled.
=> Conditionally log warning when adding labels

.ci/linting.groovy
Use `GIT_BASE_COMMIT` since it's the variable with the current commit therefore all the integrations should keep working as is.
=> linting: use the GIT_BASE_COMMIT env variable

Jenkinsfile
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Use an jenkins agent with qemu support.
* Enable aarch wheels creation. 
Closes #1151
=> Add support to release aarch64 wheels (Close #1151)

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/botocore.py, tests/instrumentation/asyncio_tests/aiobotocore_tests.py, tests/instrumentation/botocore_tests.py
=> add specific support for SQS delete/delete_batch

CHANGELOG.asciidoc, elasticapm/handlers/logbook.py, elasticapm/handlers/logging.py, tests/handlers/logbook/logbook_tests.py, tests/handlers/logging/logging_tests.py
When a LogRecord has a non-string as the `.msg` attribute,
just trying to concatenate it with `"\n"` leads to an error.
A similar problem also existed in the LogBook handler.
This error was first reported in #1340, but it wasn't obvious due to a chained exception.
closes #1340
=> fix errorhandling of LoggingHandler.emit

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/asyncio/aiobotocore.py, elasticapm/instrumentation/packages/botocore.py, tests/instrumentation/botocore_tests.py
For SQS, span links are implemented by instrumenting ReceiveMessage and attaching a reference to each messages TraceParent as a span link to the ReceiveMessage span.
closes #1473
=> implement span links for SQS ReceiveMessage

docs/configuration.asciidoc
While the previous snippet wasn't necessarily bad, it used
uuid4 for something it isn't intended to. Python 3 provides
a cryptographically secure token generator, so let's tell
our users to use that instead.
=> provide better snippet for secret token generation

docs/serverless.asciidoc
This PR updates the _Monitoring AWS Lambda Python Functions_ guide to refer to the `Elastic APM AWS Lambda extension` by its complete name.
For https://github.com/elastic/apm-aws-lambda/issues/209.
Note: The referenced attribute (`{apm-lambda-ext}`) is defined [here](https://github.com/elastic/docs/blob/7bd515547f91733dfd4ebe52932dfe4fc3547041/shared/attributes.asciidoc#L393).
=> docs: consistent naming of APM AWS Lambda extension

elasticapm/contrib/django/client.py, tests/contrib/django/django_tests.py
A bad value for the `port` in a django request would result in an uncaught `ValueError` when urllib tried to cast it to an `int`. This fixes that issue.
closes #1589
=> Fix exception for bad port in Django request

elasticapm/instrumentation/packages/asyncio/aioredis.py, elasticapm/instrumentation/packages/redis.py
It appears possible in at least come versions of the python redis libraries (redis-py and aioredis) to end up with ports that are stored as strings, whereas apm-server is expecting an int, which results in parsing issues. This preemptively casts all redis ports to ints before building the destination info.
=> cast redis ports to int

CHANGELOG.asciidoc, elasticapm/utils/__init__.py
We use `varmap()` to apply [`shorten()`](https://github.com/elastic/apm-agent-python/blob/02ed26d2b41be2cd8ba7d08f3513cddfcd06cbfe/elasticapm/utils/encoding.py#L179) recursively across a data structure. `varmap()` was recursing into the data structures, and _then_ applying the `func()` (in this case, `shorten()`) on the way back out of recursion. This meant that when shortening local variables where just recursing over the data structure was a performance issue, setting `ELASTIC_APM_LOCAL_VAR_LIST_MAX_LENGTH` wouldn't actually affect the runtime, just the output.
With this change, dictionaries and lists will be shortened and _then_ we'll iterate over their contents. Shouldn't affect `_sanitize()` at all, but will speed up `shorten()` considerably.
I think the test surface on this function …
=> Fix varmap to apply func before recursion

elasticapm/utils/__init__.py
I merged #1593 before following up on #1592 -- @kohlmanj-hs had an excellent recommendation there to simplify my logic from #1593. Thus, this PR.
=> Simplify logic in varmap

elasticapm/traces.py, tests/client/client_tests.py
`elasticapm.label(. . .)`no longer fails when no client is present
closes #1595
=> label no longer fails when called without a client

.ci/.jenkins_exclude.yml, .ci/.jenkins_framework_full.yml, docs/supported-technologies.asciidoc, tests/requirements/reqs-aiopg-newest.txt, tests/requirements/reqs-psycopg2-2.7.txt
No barriers to upgrade `psycopg2` that I can detect, and the old version was
failing DB granularity tests.
This fixes the failing tests on `main`.
Ref #1585
=> Remove psycopg2 2.7 testing/support

CHANGELOG.asciidoc, elasticapm/contrib/serverless/aws.py, tests/contrib/serverless/aws_lurl_test_data.json, tests/contrib/serverless/aws_tests.py
Adds `lambda url` support to our aws serverless integration. Since lambda urls just use the API v2 payload, it worked fine before, but this just adds granularity in the cloud.origin.service.name field.
Spec: https://github.com/elastic/apm/pull/669
=> Add lambda url granularity to lambda integration

CHANGELOG.asciidoc, elasticapm/events.py, tests/client/exception_tests.py
Restricts the length of the `message` field for exceptions captured by the agent. Continuation of the theme in #305.
Closes #1614
=> Restrict length of exception messages

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/elasticsearch.py, tests/instrumentation/elasticsearch_tests.py
Checks if the span object is non-`None` before trying to access its context.
No test attached. I've been unable to get one to fail even without the fix....it may be that we're missing something in the user's edge case. In any case, I think this is a change that should fix the user's issue, and is extremely low-risk. So I think we can forgo the test.
Closes #1615
=> Fix error with elasticsearch(sniff_on_start=True)

elasticapm/instrumentation/packages/asyncio/elasticsearch.py
Adds the same `Span` checks to the async version of our elasticsearch instrumentation to match the sync version.
Ref #1618 #1615
=> Add dropped/missing span check to async elasticsearch

elasticapm/contrib/serverless/aws.py, tests/contrib/serverless/aws_tests.py
The final merged [spec](https://github.com/elastic/apm/pull/669) removed the request ID for ELB triggers, and narrowed the `service.origin.name`. With this PR our implementation matches the [current spec](https://github.com/elastic/apm/blob/94f7e37b658896bd79146c036c44024caf6e0993/specs/agents/tracing-instrumentation-aws-lambda.md)
Closes #1622
Ref #1605 and #1609
=> Finish up ELB changes from final merged spec

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/asyncio/aiobotocore.py, elasticapm/instrumentation/packages/botocore.py, tests/instrumentation/botocore_tests.py
Adds `span.context.http.request.id` with the AWS request ID to all botocore requests.
This field is not in the intake yet, but [will be in 8.5.0](https://github.com/elastic/apm-server/issues/7871)
Closes #1524
=> Add AWS Request ID to botocore span context

CHANGELOG.asciidoc, elasticapm/transport/base.py, tests/transports/test_base.py
It turns out I never actually tested the functionality for sending an empty request with `flushed=True` when an explicit flush is called with no data on the buffer. The function signature was wrong (😅), and we also can't POST with a `None` body, we need an empty dict for the body.
Luckily, it should be rare to hit this issue because we usually flush before we've had a chance to send the contents of the buffer, and that `flushed=True` worked fine.
This fixes those issues and adds a test for this explicit case.
Thanks to @josef-cech-acc for catching this.
Closes #1627
=> Fix empty flushed=True request for forced flushes

CHANGELOG.asciidoc, elasticapm/contrib/django/management/commands/elasticapm.py, tests/contrib/django/django_tests.py
Avoids warning about an incorrect SERVER_URL when the tool is not in use.
=> Disable checks when elastic_apm is disabled

CHANGELOG.asciidoc, elasticapm/contrib/flask/__init__.py
properly set transaction outcome for flask instrumentation when an exception occurs
Closes [#1636](https://github.com/elastic/apm-agent-python/issues/1636)
=> properly set transaction outcome

docs/sanitizing-data.asciidoc, elasticapm/contrib/flask/__init__.py, elasticapm/contrib/starlette/__init__.py
In this PR some references to APP_NAME env/config variable are taken out from the documentation. According to [the code](https://github.com/elastic/apm-agent-python/blob/77c2c0d01a86a4904b669172424c926f9245beec/elasticapm/conf/__init__.py#L542) and the [elastic docs](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-service-name).
This should be some leftovers of the [v2.0.0 release](https://github.com/elastic/apm-agent-python/blob/main/CHANGELOG.asciidoc#v200---20180206)
=> No issue: Fix APP_NAME references

.ci/.jenkins_framework.yml, tests/contrib/asyncio/starlette_tests.py, tests/requirements/reqs-starlette-newest.txt
Starlette 0.21 moved to httpx as base for the TestClient
=> fix starlette 0.21 tests

elasticapm/base.py, elasticapm/transport/http.py, tests/transports/test_urllib3.py
As @trentm reported in #1634, our agent sends headers with the version sniffing request that don't really make sense. We previously fixed a similar issue for the `get-config` request (#783). To avoid similar issues in the future, these two headers are now added explicitly when POSTing new events, instead of having them as default and needing to remember to remove them for other calls.
closes #1634
=> only use content-type and content-encoding headers for POSTing events

elasticapm/instrumentation/packages/pymongo.py, tests/instrumentation/pymongo_tests.py
=> fix errors in pymongo tests introduced in #1639

elasticapm/transport/http.py, tests/transports/test_urllib3.py
Handling of negative values is not implemented, as this is not allowed per RFC: https://www.rfc-editor.org/rfc/rfc7234#section-5.2.2.8
closes #1645
=> Use minimum of 5 seconds for interval between central config calls

elasticapm/contrib/asyncio/traces.py, elasticapm/contrib/serverless/aws.py, elasticapm/traces.py, elasticapm/utils/compat.py, elasticapm/utils/deprecation.py
This PR adds `typing.TypeVar` type hints to decorator methods. 
Closes #1654
=> Use typing.TypeVar on decorators' type hints

tests/Dockerfile, tests/scripts/docker/black.sh, tests/scripts/docker/flake8.sh, tests/scripts/docker/isort.sh
Use smaller docker images (slim) and bump the version to use the supported python version for some of the scripts
vs 
Then the docker image with all the tooling is about 2x smaller:
> REPOSITORY                                          TAG                                                                IMAGE ID       CREATED          SIZE
apm-agent-python                                    python-3.6                                                         50ecd8523761   51 seconds ago   462MB
vs
> REPOSITORY                                          TAG                                                                IMAGE ID       CREATED          SIZE
apm-agent-python                                    python-3.6                                                         8e23ab62a462   16 …
=> bump python versions and use docker slim versions

CONTRIBUTING.md, docs/upgrading.asciidoc
APM Agents are listed now in the central EOL policy table: https://www.elastic.co/support/eol
=> EOL table has been moved to central EOL Policy page

docs/lambda/configure-lambda.asciidoc, docs/serverless.asciidoc
- AWS Lambda extension docs moved from the APM Guide to their own docs. Fixing links.
- added `background` as recommended send strategy in the docs
=> Correct links to Lambda extension docs

docs/api.asciidoc
The docs for `async_capture_span` haven't quite kept up with `capture_span`.
=> sync async_capture_span docs with capture_span

Jenkinsfile
Should fix the upload "failure" as seen here: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/v6.13.0/1/pipeline
=> Remove twine upload for (now-removed) wheels

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/elasticsearch.py, tests/instrumentation/elasticsearch_tests.py
In case `track_total_hits=False`, we weren't properly checking to make sure the total hits were available.
Closes #1686
=> Handle track_total_hits=False in elasticsearch instrumentation

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/elasticsearch.py
We were setting the context directly instead of using `span.update_context` -- which meant if the span was dropped, it would throw a `KeyError`
Closes #1689
=> Use span.update_context to avoid DroppedSpan issues in Elasticsearch instrumentation

elasticapm/transport/http.py, tests/transports/test_urllib3.py
Currently our server version checks are fairly low stakes. If there are issues fetching the server version, we don't need to make them `warning` level. This sets them to `debug`.
I also added the request body to the JSON error case, as we ran into one of those recently and it was hard to debug since we didn't have the body in the logs.
=> Lower log level for server version problems

tests/docker-compose.yml
Localstack introduced some internal filesystem changes with 1.0 and deprecated the old setup with the newly released 1.3, breaking our test suite. This adapts our docker-compose setup to work with the new system.
=> update localstack setup to conform to 1.x changes

.ci/nightly.groovy, Jenkinsfile, tests/docker-compose.yml, tests/entrypoint.sh, tests/scripts/docker/run_tests.sh
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Correct nightly jobs.
* Ensure the test container is running with the right user and group id (same as Jenkins).
* Use a local docker volume for localstack in the CI context.
* Nightly jobs weren't running properly for a week.
* The following change https://github.com/elastic/apm-agent-python/pull/1705 introduced a new volume mount in the current working directory.
* In the CI context, this means that we are creating a docker container running with a root user.
* This container created files with the root user permissions.
* As a result, Jenkins isn't able to clean the workspace after each test with a localstack dependency.
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/PR-170 …
=> Correct nightly jobs

tests/scripts/docker/run_tests.sh
I was starting to get permission errors when running `./tests/scripts/docker/run_tests.sh` locally. This should take care of it.
=> when running run_tests.sh locally, make sure to use the user uid/gid

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/asyncio/elasticsearch.py
=> Properly await wrapped async call in elasticsearch

elasticapm/base.py, tests/client/client_tests.py
Happened to notice these DeprecationWarnings weren't updated when we released 6.0.0. This simplifies the warnings and the tests.
=> Fix some deprecation warnings that were missed in the 6.0.0 release

CHANGELOG.asciidoc, elasticapm/utils/disttracing.py, tests/utils/test_disttracing_header.py
Per https://w3c.github.io/trace-context/#tracestate-header-field-values
the tracestate header can have whitespace around list-members. E.g.
'vendor1=foo, vendor2=bar ,\t vendor3=baz '
Refs: https://github.com/elastic/apm-agent-rum-js/issues/1334
---
I'm fairly confident on the regex changes, but not at all on possible wider impact. I haven't followed closely how `_parse_tracestate` is used in the agent code.
=> fix: "tracestate" parsing must allow whitespace around list-members

CHANGELOG.asciidoc, docs/serverless.asciidoc, elasticapm/contrib/serverless/aws.py, tests/contrib/serverless/aws_tests.py
I still don't know why, but moving the `Client` creation inside of the function execution resulted in ~18x the billable execution time of a basic "Hello World" lambda function. Instrumentation was wayyy slower.
This PR moves the instrumentation back out to setup time, and deprecates the use of kwargs with `capture_serverless`.
The core performance fix is in the first commit: https://github.com/elastic/apm-agent-python/pull/1727/commits/ccb5b67b805008c54edafe869be78773be437941
Also implements minor spec changes from https://github.com/elastic/apm/pull/749
=> Fix lambda performance issue

elasticapm/utils/encoding.py
Copies the `value` dict before iterating in `elasticapm.utils.encoding.transform`.
Closes #1737
=> Copy dict before iterating in encoding.transform

CHANGELOG.asciidoc, docs/configuration.asciidoc, docs/django.asciidoc, elasticapm/conf/__init__.py, tests/contrib/django/django_tests.py
=> Change `server_url` default to avoid ipv6 ambiguity

CHANGELOG.asciidoc, elasticapm/base.py, tests/client/client_tests.py
Add `service.agent.activation_method` as specified in [spec](https://github.com/elastic/apm/blob/main/specs/agents/metadata.md#activation-method)
Closes #1698
=> Add service.agent.activation_method to metadata

.github/workflows/run-matrix.yml, .github/workflows/test.yml
Split the matrix items into chunks and run on multiple jobs to bypass the matrix max limit of 256 when running the full matrix.
Tested with the diff
```diff
index 2738f926..364a7cee 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,9 +28,9 @@ jobs:
uses: elastic/apm-pipeline-library/.github/actions/version-framework@current
with:
-          versionsFile: .ci/.matrix_python${{ github.event_name == 'schedule' && '_full' || '' }}.yml
+          versionsFile: .ci/.matrix_python_full.yml
-          frameworksFile: .ci/.matrix_framework${{ github.event_name == 'schedule' && '_full' || '' }}.yml
+          frameworksFile: .ci/.matrix_framework_full.yml
excludedFile: .ci/.matrix_exclude.yml
- name: Split matrix
shell: python
```
Closes …
=> Fix nightly scheduled test

.ci/update-specs.yml, .github/workflows/opentelemetry.yml, .github/workflows/update-specs.yml
Moves the update specs workflow from apm-server to the consumer using updatecli to have a "dependabot"-like experience.
```
GITHUB_TOKEN=<token>\
GIT_USER=<username> \
GIT_EMAIL=j<email> \
updatecli diff -c .ci/update-specs.yml
```
- https://github.com/elastic/observability-robots/issues/1516
=> Add update-specs updatcli workflow

.github/workflows/test.yml, scripts/run-tests.bat
Creates the status check `test / all` which can be set as required status check.
This requires the matrix items to fail in case of failing tests.
- https://github.com/elastic/observability-robots/issues/1571
=> Required Status Check

.github/workflows/test-docs.yml, .github/workflows/test.yml
Sets the `test / all` status check to green in case it's a only-docs PR and the test.yml workflow is not triggered.
This is needed to be able to set `test / all` as required status check.
- #1749
=> Set status check to success in case it's an only-docs PR

.pre-commit-config.yaml, docs/flask.asciidoc
The `psutil` is required to push the elasticapm.metrics.sets otherwise, the service is not visible in the APM > Services module. Reproduced the same in my local environment and it worked fine post installation the `psutil` pkg.
[Discuss Forum #223083](https://discuss.elastic.co/t/python-apm-agent-for-flask-doesnt-report-metrics/223083)
=> Added the psutil command with the elastic-apm[flask] installation to avoid metrics error

CHANGELOG.asciidoc, elasticapm/contrib/grpc/server_interceptor.py, tests/contrib/grpc/grpc_client_tests.py
This change handles the case when APM is not recording/disabled and `client.begin_transaction()` just returns `None`. I wasn't able to figure out how to add a test for this. Do you have an advice/hint?
* https://github.com/elastic/apm-agent-python/issues/1739
* Introduced in the initial gRPC instrumentation (https://github.com/elastic/apm-agent-python/pull/1703)
=> [GRPC] Handle non-existent transaction in server interceptor

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/botocore.py
The `handle_default` handler was not correctly nesting its destination context, which resulted in spans with an incorrect `service.name`. This meant users would see empty services in their service list (and service map) for each AWS service type, but with no transactions attached to those services. 
Ref #1054 
Closes #1764
=> Fix default botocore handler

.github/workflows/test-docs.yml
Generate junit test report file with a skipped entry for the `test-docs`
otherwise, the test-reporter will fail as no artifacts can be found
https://github.com/elastic/apm-pipeline-library/pull/2121 is the one testing this in isolation.
See https://github.com/elastic/apm-pipeline-library/runs/11788165082
=> action: test-docs workflow should create basic junit report

CHANGELOG.asciidoc, elasticapm/traces.py, tests/instrumentation/base_tests.py
We list `name` as a required argument in our [`capture_span` docs](https://www.elastic.co/guide/en/apm/agent/python/current/api.html#api-capture-span). However, if a span name is not provided, we silently set it to `None`, and it gets dropped by the APM Server (as it's a [required field](https://github.com/elastic/apm-data/blob/534660e4a1517a6bc2fbc58b1df22e92bcce7180/input/elasticapm/docs/spec/v2/span.json#L876)).
I didn't think this was acceptable behavior, so I copied what the Node agent does, and set the default to `"unnamed"` so we don't silently drop spans.
This also matches my spec change here: https://github.com/elastic/apm/pull/772
=> Add a default span name

CHANGELOG.asciidoc, elasticapm/contrib/serverless/aws.py, tests/contrib/serverless/aws_tests.py
Lambda functions can be invoked by other AWS services, such as Step Functions. In this case, the `event` will be the JSON object received from the invoking service. This means that `event` could be a list, instead of a dict, which would cause an exception to be raised. This fixes that issue, and is also a useful test of our `event` defaults.
I manually tested this with Step Functions in AWS, and also wrote a unit test.
Closes #1746
=> Lambda support for `event` formed as list

tests/utils/threading_tests.py
Skips a test that's been consistently flakey, but only on Windows
=> Skip flakey windows threading test

CHANGELOG.asciidoc, elasticapm/contrib/serverless/aws.py
After discussing this in our meeting today I don't think there's any reason to limit our support to lists. With this change we will use our defaults for any non-dict `event` object.
Ref #1775 
Ref #1746
=> Handle all non-dict `event` types in lambda

.ci/updatecli.d/update-gherkin-specs.yml, .ci/updatecli.d/update-json-specs.yml, .ci/updatecli.d/update-specs.yml
Updatecli pipelines were misconfigured hence the automation failed with
```
ACTIONS
========
WARNING: **Fallback** Please add a title to you configuration using the field 'title: <your pipeline>'
Pipeline "update-jsons-specs" failed
Skipping due to:
action stage:	"Title is too long (maximum is 256 characters)"
```
I also changed the PR title to be within the kind definition rather than within the specs.
=> updatecli: fix title since it caused errors

elasticapm/contrib/pylons/__init__.py, tests/contrib/pylons/tests.py, tests/fixtures.py
Somewhere in the test suite, we're leaking a `Client` object. I haven't been able to reproduce this, but this Pylons test in particular relies on a new `Client` being created inside of the test, and was failing because of the `get_client()` code.
This test was also leaking a `Client` object, so I fixed that too. 😅
=> Fix flakey pylons test

CHANGELOG.asciidoc, elasticapm/base.py, tests/client/client_tests.py, tests/client/dropped_spans_tests.py, tests/client/transaction_tests.py, tests/contrib/django/django_tests.py, tests/instrumentation/transactions_store_tests.py, tests/transports/test_urllib3.py
Only send activation_method if server version is 8.7.1+
I also noticed that we could have issues with 3-length version tuples. So I normalized our check_server_version to make sure inputs are 3-length, to solve this issue:
```python
>>> (7, 15) >= (7, 15, 0)
False
```
Closes #1786
=> Only send activation_method if server version is >= 8.7.1

.github/workflows/run-matrix.yml, .github/workflows/test.yml, tests/docker-compose.yml, tests/scripts/docker/run_tests.sh
~Adds the `--cache-from` option.~
~This way the build time will be shorter. If there are changes in the Dockerfile, it will still be built utilising the cache.~
~Will only work after https://github.com/elastic/apm-pipeline-library/pull/2174 is merged.~
Use daily built public docker image instead of building on every run.
- depends on https://github.com/elastic/apm-pipeline-library/pull/2174
=> Optimize CI time

.github/workflows/test.yml, setup.cfg
So far, we generate coverage data for every step of the build matrix. To be useful, these coverage files have to be combined and reported on.
As an added benefit, we can then delete the large coverage files and only keep the relatively small HTML report.
=> combine coverage data and upload a html report

CHANGELOG.asciidoc, elasticapm/transport/base.py, elasticapm/transport/exceptions.py, elasticapm/transport/http.py
The logging of the stack trace can be confusing, and does not add anything interesting that would help while debugging, as the stacktrace is always the same.
Closes #ISSUE
=> remove print_trace option in TransportException

setup.cfg, tests/requirements/reqs-base.txt
urllib3 v2.0 came out during pycon, and appears to be making our windows tests hang, and at least one failure in linux tests as well.
Ref https://github.com/elastic/apm-agent-python/issues/1816
=> Pin urllib3 to <2.0 to get tests passing

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/urllib3.py, setup.cfg, tests/client/client_tests.py, tests/client/exception_tests.py, tests/instrumentation/urllib3_tests.py, tests/requirements/reqs-base.txt
urllib3 v2.0+ introduced a change to args ordering that broke some tests. This fixes those tests (plus a stack frame test that was failing under a new version of VSCode's python extension).
The hangs that were breaking test runs for urllib3 v2.0.0 were due to a regression that has been [fixed](https://github.com/urllib3/urllib3/pull/2992) in v2.0.1. Big thanks to @pquentin, @sethmlarson, and @graingert for help with this!
Closes #1816
=> Fix tests for urllib3 v2.0.1+

setup.cfg
@sethmlarson ran into issues getting the tests running using the `tests_require` block in setup.cfg. It's way out of date, this PR just matches it to `reqs-base.txt` for now. I even took out the framework extras for simplicity.
At some point we need to figure out how to automate this. Or just drop the test_requires block altogether? If it's out of date, it's useless.
=> Update the tests_require block to match reqs-base.txt

elasticapm/contrib/serverless/aws.py, tests/contrib/serverless/aws_tests.py
Updates the failure behavior for partial transaction registering to match the NodeJS agent, as described [here](https://github.com/elastic/apm/issues/753#issuecomment-1527944886)
Ref https://github.com/elastic/apm/issues/753
Ref #1784
=> Update partial transaction failure handling and add a test

docs/release-notes.asciidoc
The [release notes](https://www.elastic.co/guide/en/apm/agent/python/current/release-notes.html) page seem to have a missing link to 6.x versions.
The 6.x versions are visible in the menu on the left
But are currently missing in the page body
=> [doc] add missing 6.x release notes link

CHANGELOG.asciidoc, docs/logging.asciidoc, setup.cfg
Adds [`ecs_logging`](https://github.com/elastic/ecs-logging-python) as a dependency, for easier log correlation setup.
Ref #1837
=> Add ecs_logging to dependencies

.ci/.matrix_framework.yml, .ci/.matrix_framework_full.yml, CHANGELOG.asciidoc, elasticapm/instrumentation/packages/psycopg.py, elasticapm/instrumentation/register.py, tests/instrumentation/psycopg_tests.py, tests/requirements/reqs-psycopg-newest.txt, tests/scripts/envs/psycopg.sh
Support Psycopg3 synchronous operations by instrumenting [`psycopg.connect`](https://www.psycopg.org/psycopg3/docs/api/module.html#psycopg.connect). Add `PsycopgInstrumentation` which adopts [`Psycopg2Instrumentation`](https://github.com/elastic/apm-agent-python/blob/main/elasticapm/instrumentation/packages/psycopg2.py#L77).
- In naming, use `psycopg` (not `psycopg3`) because Psycopg3's module name is [`psycopg`](https://pypi.org/project/psycopg/).
- This PR doesn't support Psycopg3 [asynchronous operations](https://www.psycopg.org/psycopg3/docs/advanced/async.html).
Closes #1789
=> Support Psycopg3 synchronous operations

.ci/publish-aws.sh, .github/workflows/release.yml
The last release failed: https://github.com/elastic/apm-agent-python/actions/runs/5182666794
- Add AWS default region env
- Fix docker build command
=> Fix release workflow

.github/dependabot.yml, CHANGELOG.asciidoc, dev-utils/requirements.txt
When testing a lambda container image against our new docker image, I found that the 3.8 base images they provide are using an older version of OpenSSL (`1.0.2k-fips`). `urllib3` v2.0 requires OpenSSL 1.1.1+. This PR downgrades urllib3 in our lambda layer and docker image for maximum compatibility.
=> Pin urllib3==1.26.16 for AWS Lambda compatibility

docs/api.asciidoc, docs/configuration.asciidoc, docs/opentelemetry.asciidoc
This PR fixes the links broken in https://github.com/elastic/apm-server/pull/10894.
A list of broken links is here https://github.com/elastic/apm-server/pull/10891#issuecomment-1563004781.
=> docs: fix links

.ci/.matrix_exclude.yml, tests/Dockerfile
newest release of mysqlclient requires pkg-config to build.
I also had to switch netcat to netcat-traditional, as the netcat package isn't available in the Python 3.11 base image
=> add pkg-config to test image

docs/configuration.asciidoc, elasticapm/base.py, elasticapm/conf/__init__.py, tests/client/client_tests.py
Introduce a config option to disable capturing of process args, and disable it by default.
Closes #1860
=> added include_process_args config option

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/asyncio/elasticsearch.py, elasticapm/instrumentation/packages/elasticsearch.py
When cluster information was added to elasticsearch db context, it was overwriting all other `"db"` context. This fixes that issue, while finishing up #1673's work by adding `instance` to the async elasticsearch instrumentation.
I also switched to `update_context()` for the `http` context right above the bug, just for consistency. 
Ref https://github.com/elastic/apm-agent-python/pull/1673
=> Fix lost db context in elasticsearch instrumentation + Elastic Cloud

.ci/updatecli.d/update-json-specs.yml
Update the `updatecli` pipeline for the automation regarding the json specs. 
`container_metadata_discovery.json` is a new file while `cgroup_parsing.json` has been removed. 
Otherwise the automation fails
https://github.com/elastic/apm-agent-python/actions/runs/5839738941/job/15838229833#step:3:2140
- Relates https://github.com/elastic/apm/pull/807
`tests/upstream/json-specs/cgroup_parsing.json` is not used, shall the tests be changed to accommodate the new specs?
=> updatecli: add container_metadata_discovery

CHANGELOG.asciidoc, elasticapm/base.py, elasticapm/conf/__init__.py, elasticapm/utils/__init__.py, tests/client/client_tests.py, tests/config/tests.py, tests/fixtures.py, tests/utils/tests.py
Removes the deprecated `hostname`, instead splitting it out into `detected_hostname` and `configured_hostname`. Ensure that `detected_hostname` is the FQDN wherever possible.
Closes #1824
=> Report detected/configured_hostname and fix tests

.ci/.matrix_exclude.yml, Makefile, dev-utils/requirements.txt, setup.cfg, tests/requirements/reqs-base.txt
- Restrict `wrapt` version (See #1894)
- Skip some tests that have failing wheel builds
- Add 3.12 to "asyncio" list of versions
- Upgrade `pytest` for py3.12 support
Unfortunately, the PR tests won't run py3.12 tests (https://github.com/elastic/observability-robots/issues/1729), so we'll have to merge and watch what happens on `main`.
=> Fixup tests for Python 3.12.0rc1

elasticapm/contrib/asyncio/traces.py, elasticapm/traces.py
See https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages for PEP-561 instructions. It looks like we need to add a `py.typed` file to export types. Without this in place, Mypy is not picking up the correct types for function params when using the `async_capture_span` and `capture_span` decorators.
\+ Making types for `async_capture_span` and `capture_span` decorator `__call__` params more specific. See https://mypy.readthedocs.io/en/latest/generics.html#declaring-decorators for MyPy docs related to types for decorators. Pandas has a good example that references these docs: https://github.com/pandas-dev/pandas/blob/main/pandas/_typing.py#L190.
=> Add py.typed file to indicate typing support

elasticapm/instrumentation/packages/asyncio/aiohttp_client.py, tests/upstream/json-specs/container_metadata_discovery.json
=> fix "IndexError when "url" not found in args or kwargs"

.ci/.matrix_exclude.yml, tests/transports/test_base.py
- Disable `kafka-python` tests pending https://github.com/dpkp/kafka-python/pull/2376
- Skip a couple of `api_request_size` tests that fail locally. Is 3.12's gzip implementation more efficient?
Known issues:
- This does not fix the segfault, which I can't reproduce locally. I'm crossing my fingers that this is the same issue: https://github.com/python/cpython/issues/108295
- 3.12.0rc2 (which includes the above fix) isn't up on docker yet, this is the issue for that: https://github.com/docker-library/official-images/pull/15324
As with the last py3.12 PR, the PR tests actually don't touch 3.12, so we'll merge this and see what the nightlies do.
=> More Py3.12 fixes

docs/flask.asciidoc
I didn't notice that #1903 wasn't targeted to `main`. This PR makes sure that change isn't lost when we release.
=> Merge forward from 6.x to main

CHANGELOG.asciidoc, elasticapm/instrumentation/packages/dbapi2.py, tests/instrumentation/dbapi2_tests.py
Helps with https://github.com/elastic/apm-agent-python/issues/1851
This avoids slowly looping in Python, relying more on optimised C methods. For this toy benchmark:
```python
from elasticapm.instrumentation.packages.dbapi2 import tokenize, scan
import time
sql = f"Hello $q${'Peter Pan $ ' * 1000000}$q$ at Disney World"
tokens = tokenize(sql)
start = time.time()
list(scan(tokens))
end = time.time()
print(end - start)
```
it's about 3-4x faster with this PR, and about 10x faster if there's no inner `$`.
This is nice, but probably not enough. Both with and without this PR, the code assumes that anything between 2 dollar signs is potentially a dollar quote. But according to https://www.postgresql.org/docs/15/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING:
> The tag, if any, of a …
=> Optimise handling PostgreSQL dollar quotes

CHANGELOG.asciidoc, elasticapm/contrib/serverless/aws.py, tests/contrib/serverless/aws_tests.py
Previously, we assumed `event["headers"]` would always be formed as a dict. In some cases, it can be `None`. This handles that case gracefully.
=> Ensure that lambda headers are always a dict

CHANGELOG.asciidoc, elasticapm/base.py, elasticapm/contrib/serverless/aws.py, elasticapm/instrumentation/packages/base.py, elasticapm/traces.py, elasticapm/transport/base.py, tests/contrib/serverless/aws_tests.py, tests/fixtures.py
Eliminates the `add_metadata` interaction with the transport thread. We now generate our own metadata for sending the partial transaction, and also save the extra metadata in the `Client` object so that it makes it into every future metadata build.
Also, fixed the extra span being recorded when we send the partial transaction. Fixes #1902
=> Fix race condition with extra metadata + partial transaction extra span

tests/contrib/grpc/grpc_client_tests.py
Switches to non-sending client fixture in `test_grpc_client_max_spans`. The test appeared to be causing a flakey segfault in py3.12, perhaps due to [the client being short-lived](https://github.com/elastic/apm-agent-python/issues/1916) (as it wasn't waiting for anything to be sent to the sending_elasticapm_client, or closing it in-test). It didn't actually need the sending version, so hopefully this fixes that issue 🤞
=> More py3.12 CI fixup

CHANGELOG.asciidoc, docs/flask.asciidoc, elasticapm/contrib/flask/__init__.py
Starts the deprecation process for the log shipping in Flask.
=> Remove log shipping from Flask docs, start deprecation

CHANGELOG.asciidoc, elasticapm/contrib/django/handlers.py, elasticapm/handlers/logging.py
Finishes what was started in https://github.com/elastic/apm-agent-python/pull/1918
=> Mark the old logs-as-messages shipper as deprecated

docs/set-up.asciidoc
A user noticed we had ASGI middleware and couldn't find the docs. Turns out, we never built them! This fixes that issue.
=> Fix the missing asgi-middleware docs

.pre-commit-config.yaml
Since wrapt is gone since we can remove it from exclusion paths in pre commit tools configuration.
None
=> Remove vendored wrapt paths from pre-commit config

.ci/publish-aws.sh
I noticed when I was testing our lambda layer that we don't have 3.10 and 3.11 listed as compatible runtimes. This fixes that issue.
=> Add 3.10 and 3.11 to AWS lambda compatible runtimes

.ci/.matrix_framework.yml, .ci/.matrix_framework_full.yml, .pre-commit-config.yaml, elasticapm/contrib/asgi.py, elasticapm/instrumentation/packages/asyncio/asyncpg.py, tests/requirements/reqs-asyncpg-0.28.txt
In asyncpg>=0.29, the query is passed as `kwargs["state"]` instead of as `args`.
https://github.com/MagicStack/asyncpg/commit/cbf64e18a03d69b712bab1790584fc1a4a5b2bb6
I'm not sure if all cases are tested, maybe there are untested cases to fix?
Closes #1933
=> Fix asyncpg tests to make it compatible with asyncpg>=0.29

docs/starlette.asciidoc
- Add required 'SERVER_URL' config param
- Fix import in FastAPI code example
- Use the correct variable when referring to APM client
=> Fix code examples in Starlette/FastAPI doc

tests/upstream/json-specs/container_metadata_discovery.json
*Changeset*
* https://github.com/elastic/apm/commit/7ef63617e84081139e6b79b5006c035057dc42fb
---
<Actions>
<action id="ac2f2f5613c52b74a22b99cc6b7949e09a74a2f2ed2283f7e98135ed83c6e5cd">
<h3>update-json-specs</h3>
<details id="51b51c35f35d91535097fd9395976b0be51211da0a6db79e48824e45a55d3156">
<summary>container_metadata_discovery.json</summary>
<p>1 file(s) updated with &#34;{\n  \&#34;cgroup_v1_underscores\&#34;: {\n    \&#34;files\&#34;: {\n      \&#34;/proc/self/cgroup\&#34;: [\n        \&#34;1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod90d81341_92de_11e7_8cf2_507b9d4141fa.slice/crio-2227daf62df6694645fee5df53c1f91271546a9560e8600a525690ae252b7f63.scope\&#34;\n      ]\n    },\n    \&#34;containerId\&#34;: …
=> [Automation] Update JSON specs

.ci/publish-aws.sh, elasticapm/instrumentation/packages/asyncio/dbapi2_asyncio.py, elasticapm/instrumentation/packages/asyncio/psycopg_async.py, elasticapm/instrumentation/register.py
Quick and dirty patch to introduce proper DBAPIv2 support for AsyncIO-based drivers, like psycopg. Cannot attest to full functionality but I will run on it for a while and report back or adjust if need be.
Update: Not sure why but when tried to reset my branch to run pre-commit it just closed the previous PR. So here is the new one with pre-commit hooks @basepi 
Closes https://github.com/elastic/apm-agent-python/issues/1872
=> Added Async support for DBAPI2 w/ implementation for psycopg

elasticapm/instrumentation/packages/dbapi2.py, tests/instrumentation/dbapi2_tests.py
* include object name in span name when calling procedures
* consistently use span action `exec` when calling procedures
Closes #1937
=> feat(dbapi2): include object name in procedure call spans

elasticapm/instrumentation/packages/dbapi2.py, tests/instrumentation/dbapi2_tests.py
This PR should fixes how dbapi2 extract the signature if a table name has square brackets.
I added some tests to check if the fix actually solved the problem. I hope that the test cases are enough  and cover all the possibilities. 
Please let me know if I'm missing a possible usage of the method.
Closes #1929
=> fix extract_signature dbapi2: handling square brakets in table name

docs/serverless-lambda.asciidoc
The centralized Agent configuration does not work well with the AWS Lambda because it is not supported. The problem is you will be able to add the Lambda services in the central config without an understanding of its support. So, this PR will keep an alert when creating Lambda services.
=> Added a note on centralized agent config support for AWS Lambda

.github/workflows/README.md, .github/workflows/matrix-command.yml, .github/workflows/test.yml
Adds a workflow that runs the full matrix which is triggered from a PR review comment with the content `/test matrix`
=> Add PR review comment command

elasticapm/contrib/starlette/__init__.py
Create the transaction always before the body is read to avoid discrepancies between cases where the capture_body config on or off.
Closes #1948
=> contrib/starlette: take into account body reading time

elasticapm/instrumentation/packages/dbapi2.py, tests/instrumentation/dbapi2_tests.py
Dollar quotes follow the same rules as SQL identifiers so:
SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($).
Given we are not going to write a compliant SQL parser at least handle query parameters that are simple to catch since they have a digit right after the opening $.
Refs #1851
=> instrumentation: make query scanning for dollar quotes a bit more correct

elasticapm/contrib/serverless/aws.py, tests/contrib/serverless/aws_elb_test_data.json, tests/contrib/serverless/aws_tests.py
If the event has been generated from elb or api gateway and is in the v1 format normalize headers even if they already should per https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
Event discrimination logic courtesy of nodejs apm client.
Closes #1980
=> contrib/serverless/aws: normalize headers with v1 event format

.github/workflows/release.yml
Should fix the following error when tagging a release:
The workflow is not valid. .github/workflows/release.yml (Line: 13, Col: 11):
Input full-matrix is required, but not provided while calling.
See https://github.com/elastic/apm-agent-python/actions/runs/8179350148/workflow
None
=> ci: add missing full-matrix input when using test workflow in release

.github/workflows/build-distribution.yml
It looks like since v4 only one upload for the same dir will work. See:
https://github.com/actions/upload-artifact/issues/478#issuecomment-1860038048
In the meantime we sort this out revert to v3.
Should fix:
https://github.com/elastic/apm-agent-python/actions/runs/8191161913/job/22399752533
None
=> ci: revert to actions/upload-artifact@v3 in build-distribution workflow

.github/workflows/release.yml
Switch build-distribution downloadArtifact to v3 since v4 can't find artifacts if uploaded with uploadArtifact v3.
https://github.com/elastic/apm-agent-python/actions/runs/8195374788/
=> ci: switch build-distribution downloadArtifact to v3

docs/logging.asciidoc, elasticapm/handlers/logging.py
Remove specific documentation for Python < 3.2 and deprecate the old code to be removed on next major version.
None
=> Deprecate Python < 3.2 logging code and and remove documentation

.github/community-label.yml, .github/labeler-config.yml, .github/workflows/labeler.yml
Stop using the apm group and custom github action to check if issues are from internal members or not.
Closes #2001
=> ci: update issue labeler

.ci/.matrix_exclude.yml, .ci/.matrix_framework.yml, .ci/.matrix_framework_full.yml, tests/contrib/django/django_tests.py, tests/requirements/reqs-celery-5-django-5.txt, tests/requirements/reqs-django-4.2.txt, tests/requirements/reqs-django-5.0.txt
Add Django 4.2 LTS and Django 5.0 to test matrix. While at it remove some tests that runs only on old and not tested versions. Remove a couple of old not LTS versions from the default test matrix to avoid making it slower.
Closes #1946
=> Add Django 4.2 LTS and Django 5.0 to test matrix

.ci/.matrix_exclude.yml, .ci/.matrix_framework.yml, .ci/.matrix_framework_full.yml, .gitignore, docs/supported-technologies.asciidoc, tests/requirements/reqs-flask-2.1.txt, tests/requirements/reqs-flask-2.2.txt, tests/requirements/reqs-flask-2.3.txt, tests/requirements/reqs-flask-3.0.txt
Add flask 2.1+ and 3.0 to matrix
None
=> ci: add Flask 2.1+ and 3.0 to matrix

.github/workflows/packages.yml
* Set ELASTIC_CI_POST_VERSION only when needed.
* The literal value `''` is coerced to false and, as a result, the environment variable is always set on tag release.
Closes #2015
=> fix: only set ELASTIC_CI_POST_VERSION when needed (Closes #2015)

elasticapm/base.py, elasticapm/utils/json_encoder.py, elasticapm/utils/simplejson_encoder.py, tests/client/client_tests.py, tests/requirements/reqs-base.txt, tests/utils/json_utils/tests_simplejson.py
This PR introduces a new JSON serialization using simplejson that does a stricter serialization encoding floats like nan, +inf and -inf to null.
Then it makes the json serialization configurable from outside. 
Refs #1886
=> Add ability to override default serialization

tests/requirements/reqs-flask-2.0.txt
Add missing constraint on werkzeug version that does not make flask working
Hopefully fix red tests
=> tests: require Werkzeug < 3 for flask 2.0 tests

CONTRIBUTING.md, tests/scripts/docker/run_tests.sh
Use the subcommand instead of docker-compose script that for some reason it's not found anymore in ci. See https://github.com/elastic/apm-agent-python/actions/runs/8524954266/job/23350786476
=> Use docker compose subcommand instead of docker-compose

.github/workflows/release.yml
See https://github.com/elastic/apm-agent-python/pull/2014#discussion_r1576556806
Thanks @trentm 
I created a test feature branch:
- https://github.com/elastic/apm-agent-python/actions/runs/8813326799
https://github.com/elastic/apm-agent-python/attestations/748017
=> github-action: use container image for provenance

.github/actions/packages/action.yml, .github/workflows/packages.yml, .github/workflows/release.yml
> The attestations permission is necessary to persist the attestation.
As per [docs](https://github.com/github-early-access/generate-build-provenance?tab=readme-ov-file#usage)
GitHub scope for forked repositories won't have write access to anything.
=> github-action: add attestations scope

.github/workflows/release.yml
Use https://github.com/docker/metadata-action/tree/8e5442c4ef9f78752691e2d8f8d19755c6f78e81/?tab=readme-ov-file#typeref to get the tags/annotations/labels
Use sha commit for the github action related to docker.
See https://github.com/elastic/apm-agent-python/actions/runs/8879068667
```
tags: docker.elastic.co/observability/apm-agent-python:test-latest
labels: org.opencontainers.image.created=2024-04-29T13:04:44.8[6](https://github.com/elastic/apm-agent-python/actions/runs/8879068667/job/24375994029#step:6:6)6Z
org.opencontainers.image.description=Official Python agent for Elastic APM
org.opencontainers.image.licenses=BSD-3-Clause
org.opencontainers.image.revision=[7](https://github.com/elastic/apm-agent-python/actions/runs/8879068667/job/24375994029#step:6:7)ea253bd5942e0e0782449edba9ee78f …
```
=> ci: use docker/metadata-action to gather tags/labels 

tests/docker-compose.yml
Pin mysql image in tests docker-compose at 8.0 because 8.4.0 does not appear to work out of the box.
Current mysql image:
```
Waiting for mysql:3306
mysql: forward host lookup failed: Host name lookup failure
```
=> tests: pick mysql image tagged as 8.0

tests/requirements/reqs-flask-1.0.txt
Unfortunately flask 1.0 does not work with jinja 3.1.x:
```
venv/lib/python3.10/site-packages/flask/__init__.py:19: in <module>
from jinja2 import Markup, escape
E   ImportError: cannot import name 'Markup' from 'jinja2'
```
=> tests: revert bumping jinja2 in flask 1.0 tests

elasticapm/base.py
It's always available since 3.2 and tests are already assuming that.
None
=> Assume os.getppid is always available

.github/workflows/release.yml, Dockerfile.wolfi
Release two flavours of Docker images:
- the one we always do
- the one based on [Wolfi](https://www.chainguard.dev/unchained/introducing-wolfi-the-first-linux-un-distro) from [Chainguard](https://edu.chainguard.dev/chainguard/chainguard-images/overview/) 
Please note that we are going to preserve the current `Dockerfile`, so that users will still be able to build their own custom images based on `Alpine`: this is needed because `docker.elastic.co/wolfi/chainguard-base` is not a public base image, so docker build would fail for unauthenticated users.
I created a feature branch `test/docker-images-wolfi`:
- https://github.com/elastic/apm-agent-python/tree/test/docker-images-wolfi
Then I can test the release workflow without pushing any changes in production but generating docker images …
=> ci: build and push Docker image based on Chainguard base image

elasticapm/contrib/serverless/azure.py
Remove unused variable from azure implementation.
None
=> contrib/serverless: remove aws reference from azure implementation

.github/actions/build-distribution/action.yml, .github/workflows/release.yml
Hopefully fix:
```
The lambda layer can be published as follows for dev work:
aws lambda --output json publish-layer-version --layer-name 'runner-dev-elastic-apm-python' --description 'runner dev Elastic APM Python agent lambda layer' --zip-file 'fileb://build/dist/elastic-apm-python-lambda-layer.zip'
Run actions/upload-artifact@v4
with:
name: build-distribution
path: ./build/
if-no-files-found: error
compression-level: 6
overwrite: false
env:
...
With the provided path, there will be 636 files uploaded Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
None
=> ci: use v3 artifact APIs for build-distribution

.ci/.matrix_framework.yml, tests/requirements/reqs-starlette-0.13.txt, tests/requirements/reqs-starlette-0.14.txt
Fix requirements after dependabot bump. While at it run more tests before merging to avoid regressions.
=> Fix starlette requirements

elasticapm/contrib/asgi.py, elasticapm/contrib/starlette/__init__.py, tests/contrib/asgi/app.py, tests/contrib/asgi/asgi_tests.py, tests/contrib/asyncio/starlette_tests.py
Set the outcome based on the status code of the http.response.start ASGI message instead of relying only on the raise of an exception both in asgi and starlette integrations.
None
=> contrib/starlette: fix outcome for 500 responses without exception

.ci/.matrix_exclude.yml, .ci/.matrix_framework.yml, .ci/.matrix_framework_full.yml, docs/supported-technologies.asciidoc, tests/requirements/reqs-celery-4-django-1.11.txt, tests/requirements/reqs-celery-4-django-2.0.txt, tests/requirements/reqs-celery-4-flask-1.0.txt, tests/requirements/reqs-celery-4.txt
With latest pip 24.1 Celery 4 is not installable anymore because the latest release version in 2020 contains an invalid metadata:
```
WARNING: Ignoring version 4.4.7 of celery since it has invalid metadata: Requested celery<5,>4.0 from celery-4.4.7-py2.py3-none-any.whl (from -r tests/requirements/reqs-celery-4.txt (line 1)) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
pytz (>dev)
~^
Please use pip<24.1 if you need to use this version.
```
The alternative would be to upgrade pip to a fixed version (24.0) but celery 5 is out since 2020 so hopefully there's not many users left.
None
=> ci: remove celery 4 testing

.github/workflows/release.yml
Authenticate to AWS with OIDC (keyless) instead of credentials
Closes #ISSUE
=> Use elastic/oblt-actions/aws/auth action to authenticate with AWS

.ci/create-arn-table.sh, CONTRIBUTING.md
Automate the details block step described in https://github.com/elastic/apm-agent-python/blob/main/CONTRIBUTING.md#releasing (last step)
> Edit and publish the [draft Github release](https://github.com/elastic/apm-agent-python/releases) created by Github Actions. Substitute the generated changelog with one hand written into the body of the release and move the agent layer ARNs under a `<details>` block with a summary.
The manual editing of the draft is causing a malformed markdown table
Source: https://github.com/elastic/apm-agent-python/releases/tag/v6.22.3
Closes #ISSUE
=> Automate collapsing ARN table in release notes

elasticapm/instrumentation/packages/kafka.py, tests/instrumentation/kafka_tests.py
Handle the case where if the transaction is not sampled capture_span will return None instead of a span.
While at it fix handling of checking for KAFKA_HOST in tests.
Closes #2073
=> instrumentation/kafka: fix handling consumer iteration if transaction not sampled

elasticapm/contrib/django/handlers.py, elasticapm/contrib/flask/__init__.py, elasticapm/contrib/opentracing/__init__.py, elasticapm/handlers/logging.py, tests/handlers/logging/logging_tests.py
Promote the removal of opentracing integration and the removal of logging handling to DeprecationWarnings.
Refs #2029
=> Promote some PendingDeprecationWarning to DeprecationWarning

elasticapm/contrib/serverless/aws.py
Add a small note in capture_serverless docstring that with the APM layer it is already been called and adding it manually will result in instrumenting the handler twice.
=> contrib/serverless: capture_serverless is already called by the APM layer

elasticapm/transport/base.py, elasticapm/transport/http.py, tests/transports/test_urllib3.py
We have a race condition at http transport shutdown where our atexit handler is racing against urllib3 ConnectionPool weakref finalizer. Having the urllib3 finalizer called before atexit would lead to have our thread hang waiting for send any eventual queued data via urllib3 pools that are closed.
Force the creation of a new PoolManager so that we are always able to flush.
Closes #1975
=> elasticapm/transport: specific shutdown handling for http transport

tests/scripts/run_tests.sh
For some reason twisted tests are now failing with not so recent setuptools versions: 56.0 fails but 59.6.0 works.
Twisted fails to install with:
```
File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'setuptools.command.build'
```
See https://github.com/elastic/apm-agent-python/actions/runs/10107295945
=> tests: bump setuptools to latest in the script running tests

scripts/run-tests.bat, setup.py
Remove the support for `python setup.py test` for compatibility with setuptools>=72 that removed the test command.
See https://github.com/pypa/setuptools/issues/931
While at it remove some python 2 relics from windows scripts.
CI failures
```
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [18 lines of output]
<string>:60: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
main()
File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_proces …
```
=> Drop `setup.py test`

renovate.json
As far as I know, we use Dependabot for all the dependencies and Renovate only for the chainguard. See https://github.com/elastic/apm-agent-nodejs/pull/4151/commits/5083fd0598a602753fa4cf7dcbdf75e7fe4e9e66
Closes #ISSUE
=> renovate: enable only for chainguard

.github/workflows/run-matrix.yml
From latest release upload artifact will ignore hidden files by default, configure to don't ignore them when uploading coverage data.
Should fix:
```
Run actions/download-artifact@v3
Starting download for coverage-reports
Error: Unable to find an artifact with the name: coverage-reports
```
=> ci: fix upload of codecov data

.github/workflows/labeler.yml
Use GH app for creating ephemeral tokens instead of using a finer-grained token
Closes #ISSUE
=> github-actions: use ephemeral tokens

.github/workflows/release.yml, .github/workflows/test.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: https://github.com/elastic/apm-pipeline-library has been archived in favor of 
https://github.com/elastic/oblt-actions.
Requires https://github.com/elastic/oblt-actions/pull/16 to be merged.
If there are any questions, please reach out to the @elastic/observablt-ci
=> github-action: use elastic/oblt-actions/check-dependent-jobs

dev-utils/make-packages.sh
Instead of calling setup.py. This fixes the name of built distributions to match pep625, i.e. elastic_apm instead of elastic-apm.
Closes #2159
=> Use build to create distributions

.github/workflows/microbenchmark.yml
dependabot does not bump version for githubactions using semver and 'v1', see https://github.com/dependabot/dependabot-core/issues/10924
Closes #ISSUE
=> github-actions: use v1 for the oblt-actions

.ci/updatecli/values.d/scm.yml, .ci/updatecli/values.d/update-compose.yml, .github/workflows/updatecli.yml, updatecli-compose.yaml
* Use the latest updatecli version for now
* Update policies for the specs/jsons
* Enable updatecli policies autodiscovery (but use the previous latest one, so I can test this PR)
Otherwise, https://github.com/elastic/apm-agent-go/pull/1671 won't work
🐔 🥚  since https://github.com/updatecli/updatecli/releases/tag/v0.86.0
> Sources were always executed before conditions and then targets.
With this change, sources, conditions, and targets can now depend on any other resource type to allow an advanced update scenario.
And there are errors like
```
target: target#agent-json-specs
-----------------------
**Dry Run enabled**
The shell 🐚 command "/bin/sh /tmp/updatecli/bin/68b2939c124c411192667268d8f6edefbaa79f085494796eb8122c21afdb37bf.sh" exited on error (exit code 2) with the following …
```
=> ci(updatecli): add policies autodiscovery, bump updatecli version and specs/jsons policies

.github/workflows/updatecli.yml, .tool-versions, updatecli-compose.yaml
Use `.tool-versions` to pin the [updatecli](https://www.updatecli.io/docs/prologue/quick-start/) version.
Enable auto-bump
=> ci: pin updatecli version using .tool-versions and autobump

tests/requirements/reqs-asgi-2.txt, tests/requirements/reqs-base.txt
Bump jinja2 in a couple of tests requirements files to please dependabot warnings.
=> tests/requirements: bump jinja2 to 3.1.5

elasticapm/conf/__init__.py
Make `ConfigurationError` messages more descriptive on init. This is especially useful where ENV variables are not set.
Turns this error message:
```
ERROR      {/usr/local/lib/python3.10/site-packages/elasticapm/base.py}  is not a float
```
into this:
```
ERROR      {/usr/local/lib/python3.10/site-packages/elasticapm/base.py} TRANSACTION_SAMPLE_RATE= is not a float
```
=> Add field_name to ConfigurationError messages on init

.ci/.matrix_exclude.yml, elasticapm/contrib/sanic/utils.py, tests/contrib/sanic/fixtures.py, tests/contrib/sanic/sanic_tests.py
This is a follow up of #2190 that fixes the full matrix.
We are getting a Cookie instance from Sanic that by default get translated to a dict that is not a proper type for an header. Instead convert it to its string representation.
Also use a syntax for setting cookies that work on older versions.
=> Fix sanic cookies headers serialization

.ci/.matrix_framework_full.yml, tests/docker-compose.yml, tests/scripts/envs/pymongo-3.6.sh, tests/scripts/envs/pymongo-newest.sh
=> ci: test pymongo-newest against mongodb 4.0

.ci/.matrix_framework_fips.yml, .ci/.matrix_python_fips.yml, .github/workflows/test-fips.yml, tests/config/tests.py
Schedule a weekly run for running a portion of the test suite inside a fips enabled container image.
=> Add testing against fips docker image

elasticapm/conf/__init__.py, tests/config/tests.py
Block disabling server certificate validation via `ELASTIC_APM_VERIFY_SERVER_CERT` in fips mode
This requires to add validation support to _BoolConfigValue
Closes #2228
=> Make server certificate verification mandatory in fips mode

tests/instrumentation/kafka_tests.py
Use a big hammer in the meantime we find a proper solution and catch all exceptions.
Closes #2235
=> tests/kafka: silence errors arounds create and delete topics

.github/actions/build-distribution/action.yml, .github/actions/packages/action.yml, .github/workflows/docs-build.yml, .github/workflows/docs-cleanup.yml, .github/workflows/labeler.yml, .github/workflows/matrix-command.yml, .github/workflows/microbenchmark.yml, .github/workflows/packages.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/run-matrix.yml, .github/workflows/test-docs.yml, .github/workflows/test-fips.yml, .github/workflows/test-reporter.yml, .github/workflows/test.yml, .github/workflows/updatecli.yml
replace mutable tag with commit hash to improve security and reproducibility
Closes #ISSUE
=> ci: pin actions to specific commits

docs/reference/upgrading-4-x.md, docs/reference/upgrading-5-x.md, docs/reference/upgrading-6-x.md, docs/release-notes/index.md
=> [docs] Update mapped pages

.github/actions/build-distribution/action.yml, .github/actions/packages/action.yml, .github/workflows/docs-build.yml, .github/workflows/docs-cleanup.yml, .github/workflows/labeler.yml, .github/workflows/matrix-command.yml, .github/workflows/microbenchmark.yml, .github/workflows/packages.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/run-matrix.yml, .github/workflows/test-docs.yml, .github/workflows/test-fips.yml, .github/workflows/test-reporter.yml, .github/workflows/test.yml, .github/workflows/updatecli.yml
Reverts elastic/apm-agent-python#2236
I prefer that we don't pin versions coming from the `actions` for now.
Let's agree on this. At the moment, it requires some manual actions in our end to validate change for something we follow the GH security hardening:
- https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> Revert "ci: pin actions to specific commits"

.github/workflows/labeler.yml, .github/workflows/pre-commit.yml
Use `gh` cli to add labels
Use our pre-commit composite action: https://github.com/elastic/oblt-actions/tree/main/pre-commit
See https://github.com/elastic/apm-agent-python/pull/2254#issuecomment-2767309968
=> github-actions: replace third-party actions

.github/workflows/labeler.yml
Fixes a couple of regressions, the GH action supports issues and prs and running gh outside of the workspace.
see https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request and https://docs.github.com/en/webhooks/webhook-events-and-payloads#issues
see https://github.com/elastic/apm-agent-python/pull/2257#discussion_r2028617989
=> github-actions: support gh issues and prs

tests/transports/test_base.py
I don't know if python 3.12 changed gzip compression or what but we get a flush call for each message we send so since our message is compressed to 10 bytes lower the limit to 9 bytes to pass the check deciding to flush the buffer.
=> tests: enable transports tests poking with request_size for Python 3.12+

docs/reference/api-reference.md, docs/reference/azure-functions-support.md, docs/reference/configuration.md, docs/reference/index.md, docs/reference/lambda-support.md, docs/reference/opentelemetry-api-bridge.md
Related to https://github.com/elastic/docs-content/pull/1069
Updates links to APM, Synthetics, and Uptime pages in elastic/docs-content.
=> [docs] Update APM, Synthetics, Uptime links

tests/client/client_tests.py
Skip tests disabling verify_server_cert in fips mode because they'll fail.
=> tests: skip client verify_server_cert disabling tests in fips mode

.ci/docker/README.md, .ci/docker/util.sh, .github/workflows/build-images.yml, .github/workflows/run-matrix.yml, tests/Dockerfile, tests/docker-compose.yml, tests/scripts/docker/run_tests.sh
1. The workflow will create the docker images on demand and store in the [GitHub container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
2. Packages are now accessible at https://github.com/elastic/apm-agent-python/pkgs/container/apm-agent-python%2Fapm-agent-python-testing
3. Use the new container images
4. Less verbose docker pull output
See https://github.com/elastic/apm-agent-python/actions/runs/14772579891/job/41475033985
=> github-actions: use GitHub container registry

.ci/docker/util.sh
Test that an image exist before using it as cache, hopefully fixes first build for newly added images in build-images workflow.
=> ci: don't fail building the test docker image without a cached image

.ci/.matrix_exclude.yml, .ci/.matrix_python.yml, .ci/.matrix_python_full.yml, .ci/publish-aws.sh, Makefile, docs/reference/supported-technologies.md, setup.cfg
And start running CI against it.
Closes #2213
=> Add official support for Python 3.13

.ci/.matrix_exclude.yml
Mostly old stuff that does not compile and web frameworks importing the removed cgi module.
=> ci: more exclusions for python 3.13

docs/reference/django-support.md, docs/reference/flask-support.md
We need to have py-call-uwsgi-fork-hooks set in order to have proper handling of our threads.
While at it say that threads are enabled by default since a few releases.
Closes #2304
=> docs: update options to enable with uwsgi

tests/requirements/reqs-sanic-newest.txt
Use an older version of `tracerite` that is importable on older python versions.
See https://github.com/elastic/apm-agent-python/actions/runs/15839769440/attempts/2
=> requirements/sanic: stick with older tracerite for older python versions

docs/reference/configuration.md
Instead of asking to use the APM server CLI that has been removed in 9.0.
While at it drop the technical preview warning.
Closes #2275
=> docs/reference: create API key in Applications UI

elasticapm/instrumentation/packages/asyncio/dbapi2_asyncio.py, elasticapm/instrumentation/packages/asyncio/psycopg_async.py, elasticapm/instrumentation/packages/dbapi2.py, elasticapm/instrumentation/packages/psycopg.py, tests/instrumentation/asyncio_tests/psycopg_tests.py, tests/instrumentation/psycopg_tests.py
Adapt {Async,}CursorProxy._trace_sql to take into account other keyword arguments passed to it.
Closes #2293
=> psycopg: fix cursor execute and executemany signatures

.ci/.matrix_framework.yml, .ci/.matrix_framework_full.yml, elasticapm/contrib/serverless/azure.py, tests/contrib/serverless/azurefunctions/azure_functions_tests.py, tests/requirements/reqs-azurefunctions-newest.txt
Fix extension handling of client_class that was ignored and typo in metrics_sets arg that was mistyped.
While at it fix also a broken tests and add testing in the matrix.
Closes #2256
=> contrib/serverless/azure: fix client_class and metrics sets invocation

elasticapm/instrumentation/packages/mysql_connector.py, tests/instrumentation/mysql_connector_tests.py
The code was not working becase there was no default on getattr calls.
=> instrumentation/mysql_connector: fix connection retrieval

.ci/.matrix_exclude.yml, .ci/.matrix_python.yml, .ci/.matrix_python_full.yml, .ci/publish-aws.sh, .github/workflows/test.yml, elasticapm/__init__.py, elasticapm/base.py, setup.cfg, tests/context/test_context.py, tests/requirements/reqs-base.txt
Drop support for Python 3.7.
Refs #2029
=> Drop support for Python 3.7

elasticapm/conf/__init__.py, elasticapm/contrib/django/handlers.py, tests/contrib/django/django_tests.py
Remove django integrated log shipping
Refs #2029
=> contrib/django: remove deprecated LoggingHandler

elasticapm/contrib/flask/__init__.py, tests/contrib/flask/flask_tests.py
Remove flask log shipping integration 
Refs #2029
=> contrib/flask: remove deprecated log shipping integration

.ci/.matrix_framework.yml, .ci/.matrix_framework_fips.yml, .ci/.matrix_framework_full.yml, elasticapm/contrib/opentracing/__init__.py, elasticapm/contrib/opentracing/span.py, elasticapm/contrib/opentracing/tracer.py, setup.cfg, tests/contrib/opentracing/__init__.py, tests/contrib/opentracing/tests.py, tests/requirements/reqs-opentracing-2.0.txt, tests/requirements/reqs-opentracing-newest.txt, tests/scripts/envs/opentracing.sh
This reverts commit e4dff95d2176a152f385d431848afa71355b3a44. We want to release a minor release first and so we cannot break compatibility.
Refs #2029
=> Revert "Drop support for opentracing (#2342)"

tests/docker-compose.yml, tests/scripts/envs/pymongo-newest.sh
Because latest client uses a newer wire protocol.
=> tests: bump MongoDB latest to 4.2

CHANGELOG.asciidoc, docs/release-notes/index.md
Use proper number for mysql_connector PR.
=> docs: Fix typo in PR number for 6.24.0 changelog

docs/reference/lambda-support.md
Don't hardcode the apm layer version as 1, in 6.24.0 it's 3. While at it fix vars substitution.
=> docs: lambda layer version may not be 1
