elastic/apm-agent-python

elasticapm/contrib/flask/__init__.py
tests/contrib/celery/flask_tests.py
tests/contrib/flask/fixtures.py
tests/contrib/flask/flask_tests.py

Analogous to Django, this instruments celery tasks automatically

auto-instrument celery tasks with flask

---

.travis.yml
docs/index.asciidoc

Add link to Github repository and add docs build to travis file.

Add experimental header to docs

---

Jenkinsfile

Cleanup was run twice per test in Jenkins.

---

docs/configuration.asciidoc
docs/index.asciidoc
elasticapm/base.py
elasticapm/conf/__init__.py
elasticapm/contrib/asyncio/client.py
elasticapm/contrib/django/client.py
elasticapm/contrib/django/management/commands/elasticapm.py
elasticapm/contrib/django/middleware/__init__.py
elasticapm/contrib/flask/__init__.py
elasticapm/events.py
elasticapm/handlers/logbook.py
elasticapm/handlers/logging.py
tests/asyncio/test_asyncio_client.py
tests/asyncio/test_asyncio_http.py
tests/client/client_tests.py
tests/config/tests.py
tests/contrib/django/django_tests.py
tests/handlers/logbook/logbook_tests.py
tests/handlers/logging/logging_tests.py
tests/helpers.py

This uses a Config class to store client configuration, and to configure
the client in a uniform way.

refactored client configuration to be uniform across all supported frameworks

---

docs/configuration.asciidoc
elasticapm/base.py
elasticapm/conf/__init__.py
tests/client/client_tests.py

Also moved client tests to use pytest tests/fixtures

added validation for app_name and transport_class

---

elasticapm/contrib/django/client.py
tests/contrib/django/django_tests.py

don't coerce status code to string

---

docs/custom-instrumentation.asciidoc
docs/django.asciidoc
docs/flask.asciidoc
docs/index.asciidoc
docs/run-tests-locally.asciidoc
docs/sanitizing-data.asciidoc
elasticapm/contrib/flask/__init__.py

also added `[float]` all over the place and restructured docs a bit

added flask docs, and refactored initialization of the flask agent a bit

---

docs/configuration.asciidoc
elasticapm/conf/__init__.py
elasticapm/contrib/django/apps.py
elasticapm/contrib/django/handlers.py
elasticapm/contrib/django/middleware/__init__.py
elasticapm/contrib/flask/__init__.py
elasticapm/utils/__init__.py
tests/contrib/django/django_tests.py
tests/contrib/flask/flask_tests.py

and ensure that django handler gets the client used for registering the signal

harmonize debug handling between Django and Flask,

---

CHANGELOG.asciidoc
elasticapm/traces.py
tests/contrib/django/django_tests.py
tests/contrib/flask/flask_tests.py
tests/instrumentation/django_tests/template_tests.py
tests/instrumentation/jinja2_tests/jinja2_tests.py
tests/instrumentation/python_memcached_tests.py
tests/instrumentation/redis_tests.py
tests/instrumentation/sqlite_tests.py
tests/instrumentation/transactions_store_tests.py
tests/instrumentation/urllib3_tests.py

This change was agreed upon a while back, but fell between the cracks

finally killed the root trace

---

elasticapm/contrib/flask/__init__.py
tests/contrib/flask/flask_tests.py

fix the transaction type for flask requests

---

travis/run_tests.sh

this ensures that all postgres tests run

set POSTGRES_DB in travis run script

---

.travis.yml
elasticapm/instrumentation/packages/dbapi2.py
elasticapm/utils/encoding.py
elasticapm/utils/stacks.py

These are now reported by flake8

fix bare except statements

---

elasticapm/contrib/django/management/commands/elasticapm.py
elasticapm/traces.py

removes logo printing from "python manage.py elasticapm test"

Minor fixes on django management commands

---

elasticapm/contrib/django/management/commands/elasticapm.py
tests/contrib/django/django_tests.py

downgrade missing/insecure SECRET_TOKEN checks to warnings

---

CHANGELOG.md
Makefile
elasticapm/base.py
elasticapm/events.py
tests/client/client_tests.py
tests/fixtures.py
tests/scripts/download_json_schema.py

* timestamps are now microseconds since epoch
* ids are now 128bit hex strings

updated error format for v2

---

docs/api.asciidoc
docs/index.asciidoc

Improves cross document linking per https://github.com/elastic/apm/issues/19

Docs: version links (3x)

---

tests/fixtures.py

following moves in elastic/apm-server#1731

update paths to json schemas

---

Jenkinsfile

* Fix exception cast for some types of exceptions

[APM-CI] fix Exception to String conversion

---

docs/api.asciidoc

https://github.com/elastic/apm-agent-python/blob/d0568eac3bb8f55084c3ca2fa733f86cda32ffc5/elasticapm/traces.py#L388-L396

Fix `set_user_context` API doc

---

docs/api.asciidoc

docs: clarify tags

---

Jenkinsfile

Simplify pipeline to use the withSecretVault step which it runs `wrap` and `withEnv` steps internally.

[APM-CI] Use withSecretVault step

---

Jenkinsfile

* avoid the build fails on errors
* pass the correct Elastic search URL to the sendDataToElasticsearch step

fix: add Elasticsearch URL

---

.ci/jobs/elastic+apm-agent-python+master+periodic-full-matrix.yml

The JJBB job is failing I guess because of properties are duplicated on a YAML file

ci: fix JJBB job properties are duplicated

---

Jenkinsfile

see https://github.com/elastic/apm-agent-python/pull/486

ci(jenkins): new notifications and reports to Elasticsearch

---

.ci/downstreamTests.groovy
.ci/jobs/apm-agent-python-downstream.yml

* fix on the new downstream job
* do not build on GitHub events

ci: downstream job

---

.ci/downstreamTests.groovy

two missings variables make the job to fail at the end.

ci: fix wrapping-up

---

.ci/Jenkinsfile

ci: fix missing imports

---

.ci/Jenkinsfile
.ci/downstreamTests.groovy

* add missing xkey for exclusions
* fix downstream job name after rename

ci: add missing xkey for exclusions

---

.ci/Jenkinsfile

* set correct target branch
* change timeout to stages
* 12h wait for approval to release
* Set the stage and the build to Unstable when the release is not performed

fix: set correct target branch

---

.ci/Jenkinsfile

remove warmError from the Release stage it does not work as expected.

ci: remove warmError

---

.ci/Jenkinsfile

This is the last leftover to make it works properly

fix: remove dead code with an undefined variable

---

.ci/downstreamTests.groovy
Jenkinsfile

user error step, allow empty junit results

fix: user error step, allow empty junit results

---

.ci/Jenkinsfile
Jenkinsfile

- Optimize the sanity check implementation by using the `preCommit` step

ci: use preCommit step

---

elasticapm/transport/base.py

downgrade "queue full" message from warning to debug

---

CONTRIBUTING.md

We forgot to do this last release, and I almost forgot today as well.

Add github release step to release process

---

docs/api.asciidoc

Fixes a spelling mistake in the code example for creating a custom span.
Spelling!
No related issue.

Fixed spelling mistake in custom span example.

---

elasticapm/utils/__init__.py
tests/utils/tests.py

The changes are improving `get_url_dict` util function, to correctly parse ipv6 address.
Allows to handle request without throwing exception. More details in related issue. 
closes #648

Add support for ipv6 address format when parsing url [#648]

---

.ci/jobs/apm-agent-python-nightly-mbp.yml

Fixes an error with the JJBB syntax
Otherwise jobs are not created
closes #ISSUE

[jjbb] 1w rather than 7d

---

elasticapm/contrib/opentracing/span.py
tests/contrib/opentracing/tests.py

Adds a check if an elastic span is dropped before taking actions
on its wrapping OT span
fixes #683

check if span is a dropped span before closing it or setting tags on it

---

.ci/.jenkins_exclude.yml
.ci/.jenkins_framework.yml
.ci/.jenkins_framework_full.yml
docs/set-up.asciidoc
docs/starlette.asciidoc
docs/supported-technologies.asciidoc
tests/requirements/requirements-starlette-newest.txt

Adds Starlette/FastAPI documentation
Ref #686

Add Starlette/FastAPI documentation

---

CHANGELOG.asciidoc
docs/supported-technologies.asciidoc

Add review fixes from #697

---

Jenkinsfile

ci(jenkins): apm-its-downstream params has changed

---

tests/metrics/breakdown_tests.py
tests/requirements/requirements-psutil-5.0.txt

it's not quite clear why this happens some times on Windows,
but the error itself is extremely tiny
closes #748

fix occasional off-by-one error on Windows

---

CHANGELOG.asciidoc
elasticapm/instrumentation/packages/redis.py
tests/instrumentation/redis_tests.py

handle destination_info for UnixDomainSocketConnection correctly

---

Jenkinsfile
scripts/run-tests.bat
setup.cfg
tests/client/client_tests.py

Enables Cobetura coverage for Windows builds.
Also comments out a failing test.

Windows Cobertura coverage

---

.pre-commit-config.yaml
elasticapm/contrib/asyncio/traces.py
elasticapm/contrib/starlette/__init__.py
elasticapm/contrib/starlette/utils.py
elasticapm/contrib/tornado/__init__.py
setup.cfg
tests/bdd/api_key_tests.py
tests/client/client_tests.py
tests/contrib/asyncio/aiohttp_web_tests.py

fix black/isort issues, update isort, update known_third_party list

---

Jenkinsfile

This reverts commit f9b1600e7012cef55773099b2349173223d71655.

Revert "temporarily disable building packages (#777)"

---

docs/api.asciidoc

Fix typo 'name' -> 'result'

---

CHANGELOG.asciidoc

Add changelog for #592

---

Jenkinsfile

Skip the post stage where coverage is run if we are only changing docs.
Issue opened in private repo.

Don't run coverage on docs-only builds

---

docs/index.asciidoc
docs/supported-technologies.asciidoc
elasticapm/base.py
tests/client/client_tests.py

Sets our deprecation version for python 2 to 6.0.0
🎉 🎉 🎉

Add deprecation warnings for python 2

---

.ci/.jenkins_framework.yml
.ci/.jenkins_framework_full.yml
CHANGELOG.asciidoc
elasticapm/instrumentation/packages/pymemcache.py
elasticapm/instrumentation/register.py
setup.cfg
tests/instrumentation/pymemcache_tests.py
tests/instrumentation/python_memcached_tests.py
tests/requirements/reqs-pymemcache-3.0.txt
tests/requirements/reqs-pymemcache-newest.txt
tests/scripts/envs/pymemcache.sh

Adds instrumentation support for [`pymemcache`](https://github.com/pinterest/pymemcache)
Closes #706

Add instrumentation for pymemcache

---

Jenkinsfile

- Refactor the post build actions in functions.
- Fix the cornercase when a release happens, the `opbeans` stage does delete the workspace and the post build actions 
requires the workspace to process some files.
closes #819

ci: fix converge in releases

---

docs/logging.asciidoc

Fixes the basic structlog example in the docs so that it works.

Update structlog example to actually work

---

.ci/jobs/apm-agent-python.yml

Fixes the issues with the missing description field in the folder items.
closes #ISSUE

[jjbb]: folder description is required

---

elasticapm/utils/cgroup.py
tests/utils/cgroup_tests.py

see https://github.com/elastic/apm/issues/285

update kubernetes cgroup pattern to be more lax

---

docs/configuration.asciidoc
elasticapm/base.py
elasticapm/conf/__init__.py

Change `cloud_provider` default to True

---

elasticapm/utils/__init__.py

in varmap, iterate over a copy of the dict to avoid threading issues

---

.ci/.jenkins_windows.yml
Jenkinsfile

Skip `rc` versions but using latest stable versions.
See

ci: install python in windows but no rc versions

---

.ci/.jenkins_framework.yml
.ci/.jenkins_framework_full.yml

TFW you have no idea why the tests are failing...

Fixing eventlet tests

---

tests/transports/test_base.py

I've seen this one a few times, never got around to marking it.

Mark another windows test as flaky

---

Jenkinsfile

Fixes some issues with the workers when the python installation fails and even takes 12 minutes to fail.
```
[2020-09-02T12:13:33.561Z] By installing you accept licenses for the packages.
[2020-09-02T12:25:40.617Z] python3 not installed. An error occurred during installation:
```

[CI] python installation in windows with retry

---

Jenkinsfile

it forces the build result to SUCCESS when the unstash fails.

fix: force build result on unstash failed

---

CONTRIBUTING.md

Clarify testing requirements for contributing

---

elasticapm/utils/cloud.py
tests/utils/cloud_tests.py

Thanks to @axw who pointed this out!

Fix for machine type in GCP cloud metadata

---

CONTRIBUTING.md

Fixes some small things I found when reading through the CONTRIBUTING guide just now.
n/a

Fix some small grammatical errors in the contributing doc

---

docs/configuration.asciidoc

fix documented default value for `recording` setting

---

elasticapm/utils/cgroup.py
tests/utils/cgroup_tests.py

see https://github.com/elastic/apm/pull/344
closes #936

expand kubepods regex

---

CONTRIBUTING.md

Adding matrix tests is somewhat complicated, so it might be worth documenting it, both for ourselves as well as for community contributors.

added section on adding matrix tests to CONTRIBUTING.md

---

tests/fixtures.py
tests/scripts/download_json_schema.bat
tests/scripts/download_json_schema.sh

see https://github.com/elastic/apm-server/pull/4393

adapt JSONSchema paths to new location

---

CHANGELOG.asciidoc

(ugh, one day I'll learn that editing on GH creates a branch in the base repo, not in the fork)

updated changelog with some recent merges

---

tests/docker-compose.yml

also, update the PostgreSQL container to something less ancient

remove external ports from docker-compose.yml

---

elasticapm/transport/http.py

apparently, there are still cases where the answer could be invalid JSON,
see https://github.com/elastic/apm-agent-python/issues/562#issuecomment-730612349

be a bit more careful with decoding the APM Server get_config response to JSON

---

scripts/install-tools.bat
tests/Dockerfile
tests/scripts/docker/black.sh
tests/scripts/docker/flake8.sh
tests/scripts/docker/isort.sh
tests/scripts/run_tests.sh

see https://github.com/pypa/pip/issues/9284

pin pip to 20.3.1 due to a bug in 20.3.2

---

scripts/install-tools.bat
tests/Dockerfile
tests/scripts/docker/black.sh
tests/scripts/docker/flake8.sh
tests/scripts/docker/isort.sh
tests/scripts/run_tests.sh

This reverts commit f8977bf5c5d9921f83eed174b94cc48922bc72b2.

Revert "pin pip to 20.3.1 due to a bug in 20.3.2 (#989)"

---

docs/configuration.asciidoc

Missed the config docs for #943 
Ref #943

Add `use_elastic_excepthook` to docs

---

.ci/.jenkins_exclude.yml
.ci/.jenkins_framework.yml
.ci/.jenkins_framework_full.yml
docs/supported-technologies.asciidoc
setup.cfg
tests/requirements/reqs-django-1.10.txt
tests/requirements/reqs-django-1.8.txt
tests/requirements/reqs-django-1.9.txt
tests/requirements/reqs-django-3.1.txt

updated test matrix and supported technologies docs

---

Jenkinsfile

Enable email/slack communications when a tag release has been created
Requires https://github.com/elastic/apm-pipeline-library/pull/976

[CI] Use the releaseNotification step

---

tests/bdd/features/outcome.feature

*Changeset*
* https://github.com/elastic/apm/commit/3898c7f Add transaction and span outcome gherkin feature file (https://github.com/elastic/apm/pull/402)

test: synchronizing gherkin spec

---

tests/upstream/json-specs/error.json
tests/upstream/json-specs/metadata.json
tests/upstream/json-specs/metricset.json
tests/upstream/json-specs/span.json
tests/upstream/json-specs/transaction.json

APM agent json schema automatic sync
*Manually forced with the CI automation job.*

synchronize schema spec

---

tests/client/client_tests.py
tests/contrib/django/django_tests.py
tests/instrumentation/base_tests.py
tests/instrumentation/transactions_store_tests.py
tests/metrics/base_tests.py
tests/processors/tests.py
tests/transports/test_base.py
tests/utils/__init__.py

First attempt tried to be too smart...
see #911

second attempt at fixing spurious test failures due to logs from background threads

---

CHANGELOG.asciidoc
elasticapm/contrib/starlette/__init__.py
tests/contrib/asyncio/starlette_tests.py

Fix internal server errors for undefined routes. See issue #1075 for more detail.
closes #1075

Fix undefined routes 

---

.ci/.jenkins_exclude.yml
Makefile

add some more exclusions, and remove Python 2 from Makefile

---

Jenkinsfile

Use the new flaky analyser approach:
- elastic/apm-pipeline-library#1038

ci: use the new flaky analyser

---

.ci/.jenkins_exclude.yml

more eclusions due to collections.abc moves

---

elasticapm/instrumentation/packages/botocore.py

Avoid accessing private attributes to be a little safer from API changes
Also, introduce a way for boto3 < 1.7 to get a conformant service name.

use non-private attributes for service name and endpoint URL

---

CONTRIBUTING.md

We forgot in the past to add the new major version to the docs repo, hopefully this should avoid that from happening in the future.

added item to release checklist for updating docs repo

---

elasticapm/utils/cloud.py
tests/utils/cloud_tests.py

Spec: https://github.com/elastic/apm/blob/master/specs/agents/metadata.md#azure-app-services-optional
closes #990

implement azure app service cloud metadata collection

---

docs/supported-technologies.asciidoc
elasticapm/instrumentation/packages/botocore.py
elasticapm/traces.py
tests/instrumentation/botocore_tests.py

implement specific instrumentation for AWS SQS

---

tests/instrumentation/mysql_connector_tests.py
tests/instrumentation/mysqlclient_tests.py
tests/instrumentation/psycopg2_tests.py
tests/instrumentation/pymssql_tests.py
tests/instrumentation/pymysql_tests.py

replace remaining (deprecated) `yield_fixture` with `fixture`

---

.ci/.jenkins_exclude.yml
.ci/.jenkins_framework.yml
docs/supported-technologies.asciidoc
elasticapm/instrumentation/packages/asyncio/aiomysql.py
elasticapm/instrumentation/packages/asyncio/aioredis.py
elasticapm/instrumentation/register.py
setup.cfg
tests/instrumentation/asyncio_tests/aiomysql_tests.py
tests/requirements/reqs-aiomysql-newest.txt
tests/scripts/envs/aiomysql.sh

Add aiomysql instrumentation

---

tests/upstream/json-specs/sql_token_examples.json

*Changeset*
* https://github.com/elastic/apm/commit/d510ac7 Add test case for CQL line comment (https://github.com/elastic/apm/pull/429)

test: synchronizing json spec

---

.ci/.jenkins_framework.yml
.ci/.jenkins_framework_full.yml
docs/supported-technologies.asciidoc
tests/requirements/reqs-flask-2.0.txt

added flask 2.0 to test matrix

---

elasticapm/base.py

This should allow us to find the call chain that triggers
such a case

add stack info to "client set more than once" log message

---

elasticapm/contrib/starlette/__init__.py
tests/contrib/asyncio/starlette_tests.py
tests/fixtures.py

make sure Starlette's make_apm_client works without providing a config dict

---

.ci/.jenkins_framework.yml
.ci/.jenkins_framework_full.yml

disable starlette-newest tests until #1172 can be fixed

---

tests/docker-compose.yml

Issue spotted by the node agent devs: https://github.com/elastic/apm-agent-nodejs/pull/2133

Update to new location for mssql images

---

CHANGELOG.asciidoc
docs/configuration.asciidoc
elasticapm/conf/__init__.py
tests/handlers/logging/logging_tests.py

Ref https://github.com/elastic/apm/pull/490

Rename log_ecs_formatting to log_ecs_reformatting

---

CHANGELOG.asciidoc
elasticapm/utils/encoding.py
tests/client/exception_tests.py

Fix a bug with exception capturing for bad UUIDs
closes #1303

Fix exception capturing for bad UUIDs

---

CHANGELOG.asciidoc

added changelog entry for Prometheus histogram support

---

.ci/jobs/apm-agent-python-mbp.yml

Fixes error where new tags do not trigger releases.

Include tags in Jenkins filter

---

elasticapm/handlers/logging.py
elasticapm/handlers/structlog.py

See https://github.com/elastic/apm/pull/498

Remove .log suffix from event_dataset in logging

---

tests/client/client_tests.py

Skip flaky test on windows

---

tests/transports/test_urllib3.py
tests/utils/tests.py

Fixing warnings makes the test output more clean

Fix test warnings

---

CHANGELOG.asciidoc
docs/api.asciidoc
docs/serverless.asciidoc
docs/set-up.asciidoc
elasticapm/conf/constants.py
elasticapm/contrib/serverless/aws.py
elasticapm/traces.py
elasticapm/utils/__init__.py
tests/contrib/serverless/aws_api2_test_data.json
tests/contrib/serverless/aws_tests.py

[WIP] More lambda improvements + docs

---

CHANGELOG.asciidoc
elasticapm/contrib/aiohttp/utils.py
elasticapm/contrib/django/client.py
elasticapm/contrib/flask/utils.py
elasticapm/contrib/starlette/utils.py
elasticapm/contrib/tornado/utils.py
tests/contrib/asyncio/aiohttp_web_tests.py
tests/contrib/asyncio/starlette_tests.py
tests/contrib/asyncio/tornado/tornado_tests.py

Remove socket.encrypted field

---

elasticapm/conf/__init__.py

remove TransactionsMetricSet from metrics settings

---

Jenkinsfile

The regexp is not correct and command require an extra character to work, the new works as expected with 
* `/test` - https://apm-ci.elastic.co/job/apm-agent-python/job/apm-agent-python-mbp/job/PR-1398/5/
* `/test full ` - https://apm-ci.elastic.co/job/apm-agent-python/job/apm-agent-python-mbp/job/PR-1398/6/
* `/test benchmark` - https://apm-ci.elastic.co/job/apm-agent-python/job/apm-agent-python-mbp/job/PR-1398/7/

test: PR for testing messages

---

elasticapm/contrib/asyncio/traces.py
elasticapm/traces.py

Some recent changes have only been implemented in `capture_span`, while `async_capture_span` was forgotten. This change should avoid such issues going forward.

Unify async_capture_span/capture_span common code

---

CHANGELOG.asciidoc
elasticapm/instrumentation/packages/httpx/sync/httpcore.py

#1403 introduced a breaking change due to a refactor. This should make the sync code in line with the async version and fix the AttributeError.
closes #1422

Fix AttributeError in sync httpx instrumentation

---

elasticapm/conf/__init__.py

fix casing of exit_span_min_duration setting

---

CHANGELOG.asciidoc
docs/configuration.asciidoc
elasticapm/conf/__init__.py

use "unknown-python-service" as default service name

---

Jenkinsfile

Leftover from the main renaming for the apm-its

ci: use the apm-its/main branch

---

.ci/jobs/apm-agent-python-mbp.yml
.ci/jobs/apm-agent-python-nightly-mbp.yml
CONTRIBUTING.md
Jenkinsfile
README.rst
docs/run-tests-locally.asciidoc
elasticapm/instrumentation/packages/azure.py

Neutral naming: main

---

docs/api.asciidoc
docs/configuration.asciidoc
docs/getting-started.asciidoc
docs/opentracing.asciidoc

Backports relevant changes in https://github.com/elastic/apm-agent-python/pull/1449.

[6.x] Doc link fixes

---

docs/api.asciidoc
docs/configuration.asciidoc
docs/getting-started.asciidoc
docs/opentracing.asciidoc

Backports relevant changes in #1449.

[5.x] Doc link fixes

---

elasticapm/contrib/starlette/utils.py
tests/contrib/asyncio/starlette_tests.py

fix recording of status_code for starlette

---

elasticapm/instrumentation/packages/httpx/utils.py
tests/instrumentation/mysql_connector_tests.py
tests/instrumentation/mysqlclient_tests.py
tests/instrumentation/pymysql_tests.py

remove some stray print statements

---

tests/requirements/reqs-flask-1.0.txt
tests/requirements/reqs-flask-1.1.txt

limit Werkzeug version for older Flask versions

---

elasticapm/base.py
elasticapm/contrib/django/handlers.py
elasticapm/utils/compat.py
elasticapm/utils/encoding.py
tests/contrib/django/django_tests.py
tests/instrumentation/asyncio_tests/aiobotocore_tests.py
tests/instrumentation/mysql_tests.py
tests/instrumentation/transactions_store_tests.py
tests/metrics/cpu_psutil_tests.py
tests/processors/tests.py
tests/utils/encoding/tests.py

some non-black code made it into the repo, this should fix all cases.
Closes #1522

some black fixes

---

CHANGELOG.asciidoc
elasticapm/contrib/opentelemetry/span.py

Thanks to @trentm for spotting this while working on the Node implementation.

Fix missing return in opentelemetry.Span.is_recording

---

.ci/packer_cache.sh

Avoid failing while tagging and avoid pulling/tagging docker images with a comment (`#`)
Leftover from the original attempt in https://github.com/elastic/apm-agent-python/pull/1516

packer_cache: avoid failing

---

elasticapm/contrib/opentelemetry/span.py

Updates to the spec here: https://github.com/elastic/apm/pull/644
Thanks to @trentm for finding these issues.

Fix otel bridge span destination resource

---

elasticapm/contrib/starlette/utils.py

Fix on error when try to decode body thats was send with a binary file
Related to problem with other commit #1557 
closes #1556

UnicodeDecodeError_starlette_fix

---

docs/lambda/configure-lambda-widget.asciidoc
docs/lambda/configure-lambda.asciidoc

Depends on:
- https://github.com/elastic/apm-aws-lambda/pull/204

Added container image tab to lambda setup docs

---

elasticapm/instrumentation/packages/botocore.py
tests/instrumentation/botocore_tests.py

fix issue in SQS instrumentation when no MessageAttributes are set

---

CHANGELOG.asciidoc
elasticapm/instrumentation/packages/kafka.py
tests/instrumentation/kafka_tests.py

fix issues when transaction is unsampled in Kafka instrumentation

---

.ci/.jenkins_framework.yml
.ci/.jenkins_framework_full.yml
CHANGELOG.asciidoc
elasticapm/instrumentation/packages/asyncio/elasticsearch.py
elasticapm/instrumentation/packages/elasticsearch.py
tests/docker-compose.yml
tests/instrumentation/asyncio_tests/async_elasticsearch_client_tests.py
tests/instrumentation/elasticsearch_tests.py
tests/requirements/reqs-elasticsearch-8.txt
tests/scripts/envs/elasticsearch-8.sh

Add support and testing for elasticsearch-py 8.x
Closes #1617

Elasticsearch 8 support

---

.ci/.jenkins_exclude.yml

Ref https://github.com/pymssql/pymssql/issues/787

Exclude pymssql tests for python 3.6

---

elasticapm/base.py

Fix parent_id was missed when logging under leaf span

---

.ci/snapshoty.yml
Jenkinsfile

Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Add support for daily snapshots.
Validation: https://apm-ci.elastic.co/job/apm-agent-python/job/apm-agent-python-mbp/job/PR-1700/16/

Support daily snapshots

---

.ci/.jenkins_framework_full.yml
CHANGELOG.asciidoc
docs/serverless.asciidoc

Ref #1711 
Also updated the CHANGELOG for GRPC and disables grpc-1.24 for now to get the nightly tests green.

Add docs note about setup code in lambda

---

docs/configuration.asciidoc

Updated docs with a note about aws lambda configuration, see GH-1704 for more info.
Closes #1704

Config docs update with note for AWS Lambda

---

docs/configuration.asciidoc

As we're working to add more options to central config, I audited these options and they are all dynamic, and thus ready to add to central config.

Add dynamic config tag to more supported options

---

CHANGELOG.asciidoc
elasticapm/instrumentation/packages/asyncio/elasticsearch.py

When I did #1690 I forgot to update the async version of the instrumentation.
Ref #1690
Closes #1755

Fix async elasticsearch to match #1690

---

.ci/jobs/apm-agent-python-mbp.yml

Fixes typo.
https://github.com/elastic/apm-agent-python/pull/1731/

jjbb: filter by v tags

---

.ci/docker/README.md
.ci/docker/util.sh

Adds utility script for building and pushing docker images
- needed in https://github.com/elastic/apm-pipeline-library/pull/2174

Add utility script for building and pushing docker images

---

.gitignore
Makefile
tests/instrumentation/asyncio_tests/aiobotocore_tests.py
tests/instrumentation/asyncio_tests/aiomysql_tests.py
tests/instrumentation/asyncio_tests/aiopg_tests.py
tests/instrumentation/asyncio_tests/aioredis_tests.py
tests/instrumentation/asyncio_tests/async_elasticsearch_client_tests.py
tests/instrumentation/asyncio_tests/asyncpg_tests.py
tests/middleware/tests.py
tests/requirements/reqs-base.txt
tests/scripts/docker/run_tests.sh

trying to sift through our test dependency mess

---

.ci/docker/README.md

Add info on where the docker util script is mainly used.

Add info on where the docker util script is mainly used

---

tests/bdd/features/otel_bridge.feature

APM agent Gherkin specs automatic sync
*Changeset*
* https://github.com/elastic/apm/commit/047ee08de219d42c7470ef1a703c61d568e68a5a
---
<Actions>
<action id="5933bc9ee3d920b18a5219c74b073e87c76464a2df210723ce7d53bbf51eead2">
<h3>update-gherkin-specs</h3>
<details id="0d9fc0f79741b640fdbc56465ff87ce1590a46315304c680bddfaa9263ebe75a">
<summary>otel_bridge.feature</summary>
</details>
</action>
</Actions>
---
<details><summary>Updatecli options</summary>
Most of Updatecli configuration is done via Updatecli manifest.
<ul>
<li>If you close this pullrequest, Updatecli will automatically reopen it, the next time it runs.</li>
<li>If you close this pullrequest, and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
</ul>
</details>
--- …

[Automation] Update Gherkin specs

---

.github/workflows/README.md

Requires https://github.com/elastic/apm-agent-python/pull/1829

docs-ci: brief summary about the CI

---

.github/workflows/release.yml

Create and push latest docker image during release

Create and push latest docker image during release

---

tests/requirements/reqs-aiohttp-3.0.txt

Dependabot opened a [PR](https://github.com/elastic/apm-agent-python/pull/1879) here, but honestly it shouldn't have been pinned in the first place.

Unpin aiohttp req in reqs-aiohhtp-3.0.txt

---

tests/upstream/json-specs/container_metadata_discovery.json

*Changeset*
* https://github.com/elastic/apm/commit/5791498e9569ef9111615ef439e1cbf0b7fd7c18
---
<Actions>
<action id="9c61c4e961100f21a384fb44d987b9e99ed9cc1d03149e375644fab1d90353b7">
<h3>update-json-specs</h3>
<details id="51b51c35f35d91535097fd9395976b0be51211da0a6db79e48824e45a55d3156">
<summary>container_metadata_discovery.json</summary>
<p>Updated to content &#34;&#34; in file &#34;tests/upstream/json-specs/container_metadata_discovery.json&#34;&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
<td width="77">
</td>
<td>
<p>
Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
</p>
<details><summary>Options:</summary>
<br />
<p>Most of Updatecli configuration is done via <a …

[Automation] Update JSON specs

---

CHANGELOG.asciidoc

CHANGELOG for #1890

---

elasticapm/utils/cloud.py
tests/utils/cloud_tests.py

Closes: https://github.com/elastic/apm-agent-python/issues/1899

changes to metadata.cloud.project.* fields collected for GCP

---

docs/flask.asciidoc

this point is quite easy to miss out and I would like to emphasize it. 
correct the expired URL as well.
Closes #ISSUE

emphasise the flask debug mode would stop error and transactions

---

MANIFEST.in

Add py.typed to MANIFEST.in

---

docs/opentelemetry.asciidoc

Remove redundant semicolon in code example

---

.github/workflows/release.yml
.github/workflows/test.yml

- Add ability to run full matrix manually
- Runs full matrix on push (currently only `main`)
Closes #ISSUE

Add ability to run full matrix manually and on push

---

.github/workflows/test.yml

Add slack notification if scheduled or main test fails.
Closes #ISSUE

Add notification if scheduled job or main fails

---

.ci/.matrix_exclude.yml

The nightly job hasn't been running the entire test suite -- now that it is, this cleans up a few failures that have been hanging around.

Fix test suite

---

elasticapm/instrumentation/packages/urllib.py
elasticapm/utils/__init__.py
tests/client/client_tests.py
tests/fixtures.py
tests/instrumentation/urllib_tests.py
tests/utils/tests.py

Remove python 2 specific code
None

Cleanup python2 vestiges

---

.ci/.matrix_exclude.yml

Re-enable some python3.12 testing.
None

ci: re-enable more python 3.12 testing

---

.hound.yml

We have already pre-commit running on CI and it doesn't look to be running at the moment.
None

Remove hound integration

---

.github/workflows/labeler.yml

Refs: #2003
* * *
See https://github.com/elastic/apm-agent-python/issues/2001#issuecomment-2005541794 for details.

ci: fix labeler workflow syntax

---

docs/supported-technologies.asciidoc

Update docs to match the test matrix
None

docs: Add Django 4.2 and 5.0 to supported

---

CONTRIBUTING.md

Add more hints on how to release a new version of the agent
Closes #1991

CONTRIBUTING: add more hints on what is required to cut a release

---

CONTRIBUTING.md

Create a PR from a branch already rebased so that the commit list in the github UI is clean.

CONTRIBUTING: describe how to create the pr to the vX.x branch

---

tests/upstream/json-specs/metadata.json

APM agent json server schema automatic sync
*Changeset*
* https://github.com/elastic/apm-data/pull/255
* https://github.com/elastic/apm-data/commit/a76e999543efb3ba803c9a57dd13a4f6b3ffa7e1
---
<Actions>
<action id="e6053744e64b539ede7437649ecf7d637913c0598fb171b92bce658f36886c7c">
<h3>update-specs</h3>
<details id="fa450b1827de4f90bb214eaf9924527a95b821d8f72de0b38a8f5b75ac6dcdc2">
<summary>APM agent json server schema a76e999543efb3ba803c9a57dd13a4f6b3ffa7e1</summary>
<p>ran shell command &#34;tar -xzf /home/runner/work/apm-agent-python/apm-agent-python/json-schema.tgz &amp;&amp; git --no-pager diff&#34;</p>
</details>
<a href="https://github.com/elastic/apm-agent-python/actions/runs/8579165925">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
<td width="77">
</td> …

[Automation] Update JSON server schema specs

---

.github/workflows/release.yml
.github/workflows/test.yml

Use GitHub secrets.
We plan to use Keyless in a follow-up but for now this is the very last thing that required access to Vault.

github-actions: use slack and aws gh secrets

---

.github/workflows/release.yml

Add necessary permissions to use aws/auth action

---

tests/requirements/reqs-elasticsearch-7.txt
tests/requirements/reqs-elasticsearch-8.txt
tests/requirements/reqs-pymssql-newest.txt

Limit to the latest release that ships wheels for older Pythons.

Fix failures in docker tests with latest Pymssql and older python versions

---

.github/workflows/labeler.yml

github-actions: exclude bot from the triage

---

tests/config/tests.py

Add more tests for config validators
Refs #2133

tests: add more tests for validators

---

tests/requirements/reqs-pymongo-3.6.txt
tests/requirements/reqs-pymongo-newest.txt

Fix requirements that are failing on main CI.

tests: fix pymongo requirements

---

docs/release-notes/breaking-changes.md
docs/release-notes/deprecations.md
docs/release-notes/known-issues.md

Updates the navigation titles for the release notes.

Updates navigation titles for release notes

---

docs/reference/logs.md

Related to https://github.com/elastic/elasticsearch/pull/125663
Removes reliance on temporary redirects in the elasticsearch repo.

[docs] Remove reliance on temporary redirects

---

tests/requirements/reqs-base.txt

Bump to a version that has proper python metadata.

tests: bump pytest-localserver to latest
